export const queryKeys = {
  portfolios: ['portfolios'] as const,
  portfolio: (portfolioId: string) => ['portfolio', portfolioId] as const,
  portfolioSummary: (portfolioId: string) => ['portfolio', portfolioId, 'summary'] as const,
  portfolioPositionsDetails: (portfolioId: string) => ['portfolio', portfolioId, 'positions-details'] as const,

  dashboardSummary: ['dashboard', 'summary'] as const,
  portfolioAnalytics: (portfolioId: string) => ['analytics', 'portfolio', portfolioId] as const,
  portfolioAllocation: (portfolioId: string) => ['allocation', 'portfolio', portfolioId] as const,
  allocationTargets: (portfolioId: string) => ['allocation', 'targets', portfolioId] as const,
  investmentGoals: ['kyc', 'goals'] as const,
  goalProgress: ['kyc', 'goals', 'progress'] as const,
  goalContributions: (goalId: string) => ['kyc', 'goals', goalId, 'contributions'] as const,
  riskAlerts: (portfolioId?: string) => ['risk', 'alerts', portfolioId ?? 'none'] as const,

  marketList: (limit = 50, offset = 0, q?: string) => ['market', 'list', { limit, offset, q: q || '' }] as const,
  newsList: (limit = 20, offset = 0, symbol?: string) => ['news', 'list', { limit, offset, symbol: symbol || '' }] as const,
  ordersList: ['orders', 'list'] as const,
  fundsSummary: ['funds', 'summary'] as const,
  transactions: ['funds', 'transactions'] as const,
  recentTrades: (limit = 20) => ['trades', 'recent', { limit }] as const,
  sectorAnalysis: ['market', 'sector-analysis'] as const,
  indices: ['market', 'indices'] as const,
  topMovers: ['market', 'top-movers'] as const,
  mostActive: ['market', 'most-active'] as const,
  turnoverCompare: ['market', 'turnover-compare'] as const,
  marketSentiment: ['analytics', 'market-sentiment'] as const,
  upcomingEvents: ['market', 'events', 'upcoming'] as const,
  marketFlows: ['market', 'flows'] as const,
  macroSnapshot: ['market', 'macro'] as const,
  stockOfTheDay: ['research', 'stock-of-the-day'] as const,
  analystPicks: ['research', 'analyst-picks'] as const,
  earningsHighlights: ['research', 'earnings-highlights'] as const,
  themes: ['research', 'themes'] as const,

  // New
  watchlists: ['watchlists'] as const,
  watchlistItems: (watchlistId: string) => ['watchlists', watchlistId, 'items'] as const,
  alerts: ['alerts'] as const,

  // Fundamental Analysis
  fundamentalCompanyInfo: (tradingCode: string) => ['fundamentals', 'company', tradingCode] as const,
  fundamentalMarketSummary: (tradingCode: string) => ['fundamentals', 'market-summary', tradingCode] as const,
  fundamentalShareholding: (tradingCode: string) => ['fundamentals', 'shareholding', tradingCode] as const,
  fundamentalEarnings: (tradingCode: string) => ['fundamentals', 'earnings', tradingCode] as const,
  fundamentalFinancialHealth: (tradingCode: string) => ['fundamentals', 'financial-health', tradingCode] as const,
  fundamentalDividends: (tradingCode: string, limit?: number) => ['fundamentals', 'dividends', tradingCode, limit ?? 10] as const,
  fundamentalRatios: (tradingCode: string, years?: number) => ['fundamentals', 'ratios', tradingCode, years ?? 5] as const,
  fundamentalComparison: (codes: string) => ['fundamentals', 'compare', codes] as const,
  fundamentalSearch: (params: { sector?: string; category?: string; minPe?: number; maxPe?: number; minDividendYield?: number }) => 
    ['fundamentals', 'search', params] as const,
  fundamentalDataAvailability: (tradingCode: string) => ['fundamentals', 'data-availability', tradingCode] as const,
};