// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PortfolioCreate = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
};

export type PortfolioPositionPublic = {
    quantity: number;
    average_price: string;
    total_investment: string;
    current_value: string;
    unrealized_pnl: string;
    unrealized_pnl_percent: string;
    id: string;
    portfolio_id: string;
    stock_id: string;
    last_updated: string;
};

export type PortfolioPublic = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type PortfolioSummary = {
    portfolio_id: string;
    portfolio_name: string;
    total_investment: string;
    current_value: string;
    unrealized_pnl: string;
    unrealized_pnl_percent: string;
    total_positions: number;
    positions: Array<PortfolioPositionPublic>;
};

export type PortfolioUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_default?: (boolean | null);
    is_active?: (boolean | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TradeCreate = {
    trade_type: string;
    quantity: number;
    price: (number | string);
    total_amount: (number | string);
    commission: (number | string);
    net_amount: (number | string);
    trade_date: string;
    notes?: (string | null);
    is_simulated?: boolean;
    stock_id: string;
    portfolio_id?: (string | null);
};

export type TradePublic = {
    trade_type: string;
    quantity: number;
    price: string;
    total_amount: string;
    commission: string;
    net_amount: string;
    trade_date: string;
    notes?: (string | null);
    is_simulated?: boolean;
    id: string;
    portfolio_id: (string | null);
    stock_id: string;
    created_at: string;
};

export type TradeUpdate = {
    trade_type?: (string | null);
    quantity?: (number | null);
    price?: (number | string | null);
    total_amount?: (number | string | null);
    commission?: (number | string | null);
    net_amount?: (number | string | null);
    trade_date?: (string | null);
    notes?: (string | null);
    is_simulated?: (boolean | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WatchlistCreate = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
};

export type WatchlistItemCreate = {
    notes?: (string | null);
    stock_id: string;
};

export type WatchlistItemPublic = {
    notes?: (string | null);
    id: string;
    watchlist_id: string;
    stock_id: string;
    added_at: string;
};

export type WatchlistPublic = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type WatchlistUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_default?: (boolean | null);
    is_active?: (boolean | null);
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PortfolioGetUserPortfoliosResponse = (Array<PortfolioPublic>);

export type PortfolioCreatePortfolioData = {
    requestBody: PortfolioCreate;
};

export type PortfolioCreatePortfolioResponse = (PortfolioPublic);

export type PortfolioGetPortfolioData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioResponse = (PortfolioPublic);

export type PortfolioUpdatePortfolioData = {
    portfolioId: string;
    requestBody: PortfolioUpdate;
};

export type PortfolioUpdatePortfolioResponse = (PortfolioPublic);

export type PortfolioDeletePortfolioData = {
    portfolioId: string;
};

export type PortfolioDeletePortfolioResponse = (unknown);

export type PortfolioAddPositionData = {
    averagePrice: number;
    portfolioId: string;
    quantity: number;
    stockSymbol: string;
};

export type PortfolioAddPositionResponse = (PortfolioPositionPublic);

export type PortfolioGetPortfolioPositionsData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioPositionsResponse = (Array<PortfolioPositionPublic>);

export type PortfolioUpdatePositionData = {
    averagePrice?: (number | null);
    portfolioId: string;
    positionId: string;
    quantity?: (number | null);
};

export type PortfolioUpdatePositionResponse = (unknown);

export type PortfolioRemovePositionData = {
    portfolioId: string;
    positionId: string;
};

export type PortfolioRemovePositionResponse = (unknown);

export type PortfolioAddTradeData = {
    portfolioId: string;
    requestBody: TradeCreate;
};

export type PortfolioAddTradeResponse = (TradePublic);

export type PortfolioGetPortfolioTradesData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioTradesResponse = (Array<TradePublic>);

export type PortfolioUpdateTradeData = {
    portfolioId: string;
    requestBody: TradeUpdate;
    tradeId: string;
};

export type PortfolioUpdateTradeResponse = (TradePublic);

export type PortfolioDeleteTradeData = {
    portfolioId: string;
    tradeId: string;
};

export type PortfolioDeleteTradeResponse = (unknown);

export type PortfolioGetPortfolioSummaryData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioSummaryResponse = (PortfolioSummary);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WatchlistGetUserWatchlistsResponse = (Array<WatchlistPublic>);

export type WatchlistCreateWatchlistData = {
    requestBody: WatchlistCreate;
};

export type WatchlistCreateWatchlistResponse = (WatchlistPublic);

export type WatchlistGetWatchlistData = {
    watchlistId: string;
};

export type WatchlistGetWatchlistResponse = (WatchlistPublic);

export type WatchlistUpdateWatchlistData = {
    requestBody: WatchlistUpdate;
    watchlistId: string;
};

export type WatchlistUpdateWatchlistResponse = (WatchlistPublic);

export type WatchlistDeleteWatchlistData = {
    watchlistId: string;
};

export type WatchlistDeleteWatchlistResponse = (unknown);

export type WatchlistAddWatchlistItemData = {
    requestBody: WatchlistItemCreate;
    watchlistId: string;
};

export type WatchlistAddWatchlistItemResponse = (WatchlistItemPublic);

export type WatchlistGetWatchlistItemsData = {
    watchlistId: string;
};

export type WatchlistGetWatchlistItemsResponse = (Array<WatchlistItemPublic>);

export type WatchlistUpdateWatchlistItemData = {
    itemId: string;
    notes?: (string | null);
    watchlistId: string;
};

export type WatchlistUpdateWatchlistItemResponse = (WatchlistItemPublic);

export type WatchlistRemoveWatchlistItemData = {
    itemId: string;
    watchlistId: string;
};

export type WatchlistRemoveWatchlistItemResponse = (unknown);

export type WatchlistAddMultipleStocksData = {
    requestBody: Array<(string)>;
    watchlistId: string;
};

export type WatchlistAddMultipleStocksResponse = (unknown);

export type WatchlistSearchStocksData = {
    limit?: number;
    query: string;
};

export type WatchlistSearchStocksResponse = (unknown);

export type WatchlistGetWatchlistItemsWithDetailsData = {
    watchlistId: string;
};

export type WatchlistGetWatchlistItemsWithDetailsResponse = (unknown);