// This file is auto-generated by @hey-api/openapi-ts

export type AccountTransactionPublic = {
    id: string;
    type: TransactionType;
    amount: string;
    currency: string;
    description: (string | null);
    created_at: string;
    portfolio_id: (string | null);
    order_id: (string | null);
    trade_id: (string | null);
};

/**
 * Types of investment accounts
 */
export type AccountType = 'INDIVIDUAL' | 'JOINT' | 'RETIREMENT_401K' | 'RETIREMENT_IRA' | 'RETIREMENT_ROTH_IRA' | 'TRUST' | 'CORPORATE';

export type AlertCreate = {
    alert_type: string;
    condition: string;
    target_value: (number | string);
    notification_method: string;
    is_recurring?: boolean;
    frequency?: (string | null);
    notes?: (string | null);
    stock_id?: (string | null);
};

export type AlertPublic = {
    alert_type: string;
    condition: string;
    target_value: string;
    notification_method: string;
    is_recurring?: boolean;
    frequency?: (string | null);
    notes?: (string | null);
    id: string;
    user_id: string;
    stock_id: (string | null);
    current_value: (string | null);
    status: string;
    last_triggered: (string | null);
    trigger_count: number;
    created_at: string;
    updated_at: string;
};

export type AlertUpdate = {
    alert_type?: (string | null);
    condition?: (string | null);
    target_value?: (number | string | null);
    notification_method?: (string | null);
    is_recurring?: (boolean | null);
    frequency?: (string | null);
    status?: (string | null);
    notes?: (string | null);
};

export type AllocationTargetCreate = {
    category: string;
    category_type?: string;
    target_percent: (number | string);
    min_percent?: (number | string | null);
    max_percent?: (number | string | null);
};

export type AllocationTargetPublic = {
    category: string;
    category_type?: string;
    target_percent: string;
    min_percent?: (string | null);
    max_percent?: (string | null);
    id: string;
    user_id: string;
    portfolio_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Annual earnings summary
 */
export type AnnualEarnings = {
    prev_year_eps?: (string | null);
    current_year_eps?: (string | null);
    growth_percent?: (string | null);
    profit_million?: (string | null);
};

export type Body_analytics_upsert_allocation_targets = {
    targets: Array<AllocationTargetCreate>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BulkRemoveRequest = {
    item_ids?: (Array<(string)> | null);
    stock_ids?: (Array<(string)> | null);
};

export type BulkSymbolsRequest = {
    symbols: Array<(string)>;
};

/**
 * Company basic information for fundamental analysis
 */
export type CompanyBasicInfo = {
    trading_code: string;
    company_name?: (string | null);
    category?: (string | null);
    sector?: (string | null);
    listing_year?: (number | null);
    head_office?: (string | null);
    factory?: (string | null);
    contact: ContactInfo;
    website?: (string | null);
};

/**
 * Company comparison metrics
 */
export type CompanyComparison = {
    trading_code: string;
    company_name?: (string | null);
    /**
     * Last Trading Price
     */
    ltp?: (string | null);
    /**
     * P/E ratio
     */
    pe?: (string | null);
    /**
     * Dividend yield %
     */
    dividend_yield?: (string | null);
    /**
     * Net Asset Value
     */
    nav?: (string | null);
    /**
     * Market cap in millions
     */
    market_cap?: (string | null);
    /**
     * Earnings per share
     */
    eps?: (string | null);
    sector?: (string | null);
};

/**
 * Search result item
 */
export type CompanySearchResult = {
    trading_code: string;
    company_name?: (string | null);
    sector?: (string | null);
    category?: (string | null);
    /**
     * Last Trading Price
     */
    ltp?: (string | null);
    pe_ratio?: (string | null);
    market_cap?: (string | null);
};

/**
 * Company contact information
 */
export type ContactInfo = {
    company_secretary?: (string | null);
    email?: (string | null);
    cell?: (string | null);
};

/**
 * Annual dividend information
 */
export type DividendHistory = {
    year: number;
    /**
     * Cash dividend %
     */
    cash_dividend?: (string | null);
    /**
     * Stock dividend %
     */
    stock_dividend?: (string | null);
    /**
     * Dividend yield %
     */
    dividend_yield?: (string | null);
};

/**
 * Complete earnings and profit response
 */
export type EarningsProfitResponse = {
    quarters?: Array<QuarterlyEarnings>;
    annual?: (AnnualEarnings | null);
};

/**
 * Financial health and loan status
 */
export type FinancialHealth = {
    /**
     * Short-term loan in millions
     */
    short_term_loan?: (string | null);
    /**
     * Long-term loan in millions
     */
    long_term_loan?: (string | null);
    /**
     * Total loan in millions
     */
    total_loan?: (string | null);
    /**
     * Reserve and surplus in millions
     */
    reserve_and_surplus?: (string | null);
    /**
     * Debt status description
     */
    debt_status?: string;
    /**
     * Additional remarks
     */
    remarks?: string;
};

/**
 * Data availability status for a company
 */
export type FundamentalDataAvailability = {
    has_basic_info?: boolean;
    has_financial_data?: boolean;
    has_dividend_data?: boolean;
    has_shareholding_data?: boolean;
    has_loan_data?: boolean;
    has_quarterly_data?: boolean;
    latest_data_year?: (number | null);
    latest_quarter_date?: (string | null);
};

export type FundsChangeRequest = {
    amount: number;
    portfolio_id?: (string | null);
    description?: (string | null);
};

export type FundsSettingsRequest = {
    credit_limit: number;
};

/**
 * Historical financial ratios for charting
 */
export type HistoricalRatios = {
    /**
     * Historical EPS values
     */
    eps_history?: Array<(string | null)>;
    /**
     * Historical P/E ratios
     */
    pe_history?: Array<(string | null)>;
    /**
     * Historical NAV values
     */
    nav_history?: Array<(string | null)>;
    /**
     * Historical profit in millions
     */
    profit_history?: Array<(string | null)>;
    /**
     * Years for the data points
     */
    years?: Array<(number)>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Investment objectives
 */
export type InvestmentGoal = 'RETIREMENT' | 'EDUCATION' | 'WEALTH_BUILDING' | 'INCOME_GENERATION' | 'CAPITAL_PRESERVATION' | 'SHORT_TERM_GAINS';

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type KYCInformationCreate = {
    first_name: string;
    last_name: string;
    date_of_birth: string;
    ssn_last_four: string;
    phone_number: string;
    street_address: string;
    city: string;
    state: string;
    zip_code: string;
    country?: string;
    employer_name?: (string | null);
    occupation?: (string | null);
    annual_income?: (number | null);
    employment_status?: (string | null);
    net_worth?: (number | null);
    liquid_net_worth?: (number | null);
    investment_experience?: (string | null);
};

export type KYCInformationPublic = {
    first_name: string;
    last_name: string;
    date_of_birth: string;
    ssn_last_four: string;
    phone_number: string;
    street_address: string;
    city: string;
    state: string;
    zip_code: string;
    country?: string;
    employer_name?: (string | null);
    occupation?: (string | null);
    annual_income?: (number | null);
    employment_status?: (string | null);
    net_worth?: (number | null);
    liquid_net_worth?: (number | null);
    investment_experience?: (string | null);
    id: string;
    kyc_status: KYCStatus;
    verification_date?: (string | null);
    created_at: string;
    updated_at: string;
};

export type KYCInformationUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    date_of_birth?: (string | null);
    phone_number?: (string | null);
    street_address?: (string | null);
    city?: (string | null);
    state?: (string | null);
    zip_code?: (string | null);
    country?: (string | null);
    employer_name?: (string | null);
    occupation?: (string | null);
    annual_income?: (number | null);
    employment_status?: (string | null);
    net_worth?: (number | null);
    liquid_net_worth?: (number | null);
    investment_experience?: (string | null);
};

/**
 * KYC verification status
 */
export type KYCStatus = 'PENDING' | 'IN_REVIEW' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';

/**
 * Market summary and valuation metrics
 */
export type MarketSummary = {
    /**
     * Last Trading Price
     */
    ltp?: (string | null);
    /**
     * Price change
     */
    ltp_change?: (string | null);
    /**
     * Yesterday's Closing Price
     */
    ycp?: (string | null);
    /**
     * Current P/E ratio
     */
    current_pe?: (string | null);
    /**
     * Audited P/E ratio
     */
    audited_pe?: (string | null);
    /**
     * Dividend yield %
     */
    dividend_yield?: (string | null);
    /**
     * Net Asset Value per share
     */
    nav?: (string | null);
    /**
     * Face value per share
     */
    face_value?: (string | null);
    /**
     * Market capitalization in millions
     */
    market_cap?: (string | null);
    /**
     * Paid-up capital in millions
     */
    paid_up_capital?: (string | null);
    /**
     * Authorized capital in millions
     */
    authorized_capital?: (string | null);
    /**
     * Reserve and surplus in millions
     */
    reserve_and_surplus?: (string | null);
    /**
     * Financial year end date
     */
    year_end?: (string | null);
    /**
     * Last AGM date
     */
    last_agm?: (string | null);
    week_52_range: Week52Range;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NewsCreate = {
    title: string;
    content: string;
    summary?: (string | null);
    source: string;
    source_url?: (string | null);
    author?: (string | null);
    category: string;
    tags?: Array<(string)>;
    sentiment?: (string | null);
    sentiment_score?: (number | string | null);
    published_at: string;
    is_active?: boolean;
};

export type NewsPublic = {
    title: string;
    content: string;
    summary?: (string | null);
    source: string;
    source_url?: (string | null);
    author?: (string | null);
    category: string;
    tags?: Array<(string)>;
    sentiment?: (string | null);
    sentiment_score?: (string | null);
    published_at: string;
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type OrderCreate = {
    order_type: OrderType;
    side: OrderSide;
    quantity: number;
    price?: (number | string | null);
    stop_price?: (number | string | null);
    validity?: OrderValidity;
    notes?: (string | null);
    is_simulated?: boolean;
    stock_id: string;
    portfolio_id?: (string | null);
};

export type OrderExecutionPublic = {
    quantity: number;
    price: string;
    amount: string;
    commission: string;
    net_amount: string;
    executed_at: string;
    exchange_trade_id: (string | null);
    id: string;
    order_id: string;
};

export type OrderPublic = {
    order_type: OrderType;
    side: OrderSide;
    quantity: number;
    price?: (string | null);
    stop_price?: (string | null);
    validity?: OrderValidity;
    notes?: (string | null);
    is_simulated?: boolean;
    id: string;
    user_id: string;
    portfolio_id: (string | null);
    stock_id: string;
    status: OrderStatus;
    filled_quantity: number;
    average_price: (string | null);
    total_amount: (string | null);
    commission: (string | null);
    net_amount: (string | null);
    placed_at: string;
    filled_at: (string | null);
    cancelled_at: (string | null);
    expires_at: (string | null);
    exchange_order_id: (string | null);
    rejection_reason: (string | null);
};

/**
 * Order side (buy/sell)
 */
export type OrderSide = 'BUY' | 'SELL';

/**
 * Order status
 */
export type OrderStatus = 'PENDING' | 'PARTIAL' | 'FILLED' | 'CANCELLED' | 'REJECTED' | 'EXPIRED' | 'PENDING_CANCEL';

export type OrderSummary = {
    total_orders: number;
    pending_orders: number;
    filled_orders: number;
    cancelled_orders: number;
    rejected_orders: number;
    total_volume: number;
    total_amount: string;
    orders: Array<OrderPublic>;
};

/**
 * Types of orders
 */
export type OrderType = 'MARKET' | 'LIMIT' | 'STOP' | 'STOP_LIMIT';

export type OrderUpdate = {
    price?: (number | string | null);
    stop_price?: (number | string | null);
    quantity?: (number | null);
    validity?: (OrderValidity | null);
    notes?: (string | null);
};

/**
 * Order validity period
 */
export type OrderValidity = 'DAY' | 'GTC' | 'IOC' | 'FOK';

/**
 * Public order payload with stock details for UI convenience
 */
export type OrderWithDetails = {
    order_type: OrderType;
    side: OrderSide;
    quantity: number;
    price?: (string | null);
    stop_price?: (string | null);
    validity?: OrderValidity;
    notes?: (string | null);
    is_simulated?: boolean;
    id: string;
    user_id: string;
    portfolio_id: (string | null);
    stock_id: string;
    status: OrderStatus;
    filled_quantity: number;
    average_price: (string | null);
    total_amount: (string | null);
    commission: (string | null);
    net_amount: (string | null);
    placed_at: string;
    filled_at: (string | null);
    cancelled_at: (string | null);
    expires_at: (string | null);
    exchange_order_id: (string | null);
    rejection_reason: (string | null);
    symbol: string;
    company_name: string;
};

export type PaymentRequest = {
    plan_id: string;
    payment_method: string;
    amount: (number | string);
    currency?: string;
};

export type PaymentResponse = {
    payment_id: string;
    transaction_id: string;
    status: string;
    gateway_url?: (string | null);
    gateway_data?: ({
    [key: string]: unknown;
} | null);
};

export type PortfolioCreate = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
};

export type PortfolioPositionPublic = {
    quantity: number;
    average_price: string;
    total_investment: string;
    current_value: string;
    unrealized_pnl: string;
    unrealized_pnl_percent: string;
    id: string;
    portfolio_id: string;
    stock_id: string;
    last_updated: string;
};

export type PortfolioPublic = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
    cash_balance?: (string | null);
};

export type PortfolioSummary = {
    portfolio_id: string;
    portfolio_name: string;
    total_investment: string;
    current_value: string;
    unrealized_pnl: string;
    unrealized_pnl_percent: string;
    total_positions: number;
    positions: Array<PortfolioPositionPublic>;
};

export type PortfolioUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_default?: (boolean | null);
    is_active?: (boolean | null);
    cash_balance?: (number | string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Quarterly earnings data
 */
export type QuarterlyEarnings = {
    quarter: string;
    prev_year_eps?: (string | null);
    current_year_eps?: (string | null);
    growth_percent?: (string | null);
    period: string;
};

export type RiskAlertPublic = {
    alert_type: string;
    severity: string;
    message: string;
    metric_value?: (string | null);
    threshold_value?: (string | null);
    is_active?: boolean;
    id: string;
    user_id: string;
    portfolio_id: (string | null);
    created_at: string;
    resolved_at: (string | null);
};

/**
 * User risk profiles
 */
export type RiskProfile = 'CONSERVATIVE' | 'MODERATE' | 'AGGRESSIVE';

/**
 * Shareholding pattern changes
 */
export type ShareholdingChange = {
    foreign?: (string | null);
    public?: (string | null);
};

/**
 * Shareholding distribution
 */
export type ShareholdingPattern = {
    date: string;
    /**
     * Sponsor/Director %
     */
    director?: (string | null);
    /**
     * Government %
     */
    govt?: (string | null);
    /**
     * Institute %
     */
    institute?: (string | null);
    /**
     * Foreign %
     */
    foreign?: (string | null);
    /**
     * Public %
     */
    public?: (string | null);
    change?: (ShareholdingChange | null);
};

export type StockScreenerCreate = {
    name: string;
    description?: (string | null);
    criteria: {
        [key: string]: unknown;
    };
    is_active?: boolean;
};

export type StockScreenerPublic = {
    name: string;
    description?: (string | null);
    criteria: {
        [key: string]: unknown;
    };
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type SubscriptionPlanCreate = {
    name: string;
    description: string;
    price: (number | string);
    currency?: string;
    duration_days?: number;
    features?: {
        [key: string]: unknown;
    };
    is_active?: boolean;
};

export type SubscriptionPlanPublic = {
    name: string;
    description: string;
    price: string;
    currency?: string;
    duration_days?: number;
    features?: {
        [key: string]: unknown;
    };
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type SubscriptionStatus = {
    user_id: string;
    current_plan?: (string | null);
    status: string;
    start_date?: (string | null);
    end_date?: (string | null);
    is_active: boolean;
    features?: {
        [key: string]: unknown;
    };
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TradeCreate = {
    trade_type: string;
    quantity: number;
    price: (number | string);
    total_amount: (number | string);
    commission: (number | string);
    net_amount: (number | string);
    trade_date: string;
    notes?: (string | null);
    is_simulated?: boolean;
    stock_id: string;
    portfolio_id?: (string | null);
};

export type TradePublic = {
    trade_type: string;
    quantity: number;
    price: string;
    total_amount: string;
    commission: string;
    net_amount: string;
    trade_date: string;
    notes?: (string | null);
    is_simulated?: boolean;
    id: string;
    portfolio_id: (string | null);
    stock_id: string;
    created_at: string;
};

export type TradeUpdate = {
    trade_type?: (string | null);
    quantity?: (number | null);
    price?: (number | string | null);
    total_amount?: (number | string | null);
    commission?: (number | string | null);
    net_amount?: (number | string | null);
    trade_date?: (string | null);
    notes?: (string | null);
    is_simulated?: (boolean | null);
};

/**
 * Public trade payload with stock details for UI convenience
 */
export type TradeWithDetails = {
    trade_type: string;
    quantity: number;
    price: string;
    total_amount: string;
    commission: string;
    net_amount: string;
    trade_date: string;
    notes?: (string | null);
    is_simulated?: boolean;
    id: string;
    portfolio_id: (string | null);
    stock_id: string;
    created_at: string;
    symbol: string;
    company_name: string;
};

export type TransactionType = 'DEPOSIT' | 'WITHDRAWAL' | 'BUY' | 'SELL' | 'ORDER_PLACED' | 'ORDER_CANCELLED' | 'DIVIDEND' | 'FEE' | 'ADJUSTMENT';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserAccountCreate = {
    account_type: AccountType;
    account_name: string;
    account_number?: (string | null);
    joint_holder_name?: (string | null);
    joint_holder_ssn?: (string | null);
};

export type UserAccountPublic = {
    account_type: AccountType;
    account_name: string;
    account_number?: (string | null);
    joint_holder_name?: (string | null);
    joint_holder_ssn?: (string | null);
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type UserAccountUpdate = {
    account_name?: (string | null);
    account_number?: (string | null);
    is_active?: (boolean | null);
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserInvestmentGoalContributionCreate = {
    amount: number;
    contributed_at?: (string | null);
    notes?: (string | null);
};

export type UserInvestmentGoalContributionPublic = {
    amount: number;
    contributed_at: string;
    notes?: (string | null);
    id: string;
    goal_id: string;
    user_id: string;
    created_at: string;
};

export type UserInvestmentGoalCreate = {
    goal_type: InvestmentGoal;
    target_amount?: (number | null);
    target_date?: (string | null);
    priority?: number;
    description?: (string | null);
    is_active?: boolean;
};

export type UserInvestmentGoalPublic = {
    goal_type: InvestmentGoal;
    target_amount?: (number | null);
    target_date?: (string | null);
    priority?: number;
    description?: (string | null);
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type UserInvestmentGoalUpdate = {
    goal_type?: (InvestmentGoal | null);
    target_amount?: (number | null);
    target_date?: (string | null);
    priority?: (number | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRiskProfileCreate = {
    risk_profile?: RiskProfile;
    max_portfolio_volatility?: (number | string);
    max_single_position?: (number | string);
    max_sector_concentration?: (number | string);
    target_sharpe_ratio?: (number | string);
    max_drawdown_tolerance?: (number | string);
};

export type UserRiskProfilePublic = {
    risk_profile?: RiskProfile;
    max_portfolio_volatility?: string;
    max_single_position?: string;
    max_sector_concentration?: string;
    target_sharpe_ratio?: string;
    max_drawdown_tolerance?: string;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserSubscriptionCreate = {
    status: string;
    start_date: string;
    end_date: string;
    auto_renew?: boolean;
    plan_id: string;
};

export type UserSubscriptionPublic = {
    status: string;
    start_date: string;
    end_date: string;
    auto_renew?: boolean;
    id: string;
    user_id: string;
    plan_id: string;
    created_at: string;
    updated_at: string;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WatchlistCreate = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
};

export type WatchlistItemCreate = {
    notes?: (string | null);
    stock_id: string;
};

export type WatchlistItemPublic = {
    notes?: (string | null);
    id: string;
    watchlist_id: string;
    stock_id: string;
    added_at: string;
};

export type WatchlistPublic = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type WatchlistUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_default?: (boolean | null);
    is_active?: (boolean | null);
};

/**
 * 52-week price range
 */
export type Week52Range = {
    low?: (string | null);
    high?: (string | null);
};

export type AlertsListAlertsResponse = (Array<AlertPublic>);

export type AlertsCreateAlertData = {
    requestBody: AlertCreate;
};

export type AlertsCreateAlertResponse = (AlertPublic);

export type AlertsUpdateAlertData = {
    alertId: string;
    requestBody: AlertUpdate;
};

export type AlertsUpdateAlertResponse = (AlertPublic);

export type AlertsDeleteAlertData = {
    alertId: string;
};

export type AlertsDeleteAlertResponse = (void);

export type AlertsEvaluateAlertData = {
    alertId: string;
};

export type AlertsEvaluateAlertResponse = (AlertPublic);

export type AnalyticsGetPortfolioPerformanceData = {
    /**
     * Time period: 1D, 1W, 1M, 3M, 6M, 1Y, 2Y, 5Y, ALL
     */
    period?: string;
    portfolioId: string;
};

export type AnalyticsGetPortfolioPerformanceResponse = (unknown);

export type AnalyticsGetPortfolioAllocationData = {
    portfolioId: string;
};

export type AnalyticsGetPortfolioAllocationResponse = (unknown);

export type AnalyticsGetBenchmarkComparisonData = {
    /**
     * Benchmark symbol (e.g., SPY, QQQ, IWM)
     */
    benchmark?: string;
    /**
     * Time period: 1M, 3M, 6M, 1Y, 2Y, 5Y
     */
    period?: string;
    portfolioId: string;
};

export type AnalyticsGetBenchmarkComparisonResponse = (unknown);

export type AnalyticsGetDividendAnalysisData = {
    portfolioId: string;
};

export type AnalyticsGetDividendAnalysisResponse = (unknown);

export type AnalyticsGetCostBasisAnalysisData = {
    portfolioId: string;
};

export type AnalyticsGetCostBasisAnalysisResponse = (unknown);

export type AnalyticsGetMarketSentimentData = {
    days?: number;
};

export type AnalyticsGetMarketSentimentResponse = ({
    [key: string]: unknown;
});

export type AnalyticsGetAllocationTargetsData = {
    portfolioId: string;
};

export type AnalyticsGetAllocationTargetsResponse = (Array<AllocationTargetPublic>);

export type AnalyticsUpsertAllocationTargetsData = {
    portfolioId: string;
    requestBody: Body_analytics_upsert_allocation_targets;
};

export type AnalyticsUpsertAllocationTargetsResponse = (Array<AllocationTargetPublic>);

export type DashboardGetDashboardSummaryResponse = (unknown);

export type FundamentalsGetCompanyInfoData = {
    tradingCode: string;
};

export type FundamentalsGetCompanyInfoResponse = (CompanyBasicInfo);

export type FundamentalsGetMarketSummaryData = {
    tradingCode: string;
};

export type FundamentalsGetMarketSummaryResponse = (MarketSummary);

export type FundamentalsGetShareholdingPatternData = {
    tradingCode: string;
};

export type FundamentalsGetShareholdingPatternResponse = (ShareholdingPattern);

export type FundamentalsGetEarningsProfitData = {
    tradingCode: string;
};

export type FundamentalsGetEarningsProfitResponse = (EarningsProfitResponse);

export type FundamentalsGetFinancialHealthData = {
    tradingCode: string;
};

export type FundamentalsGetFinancialHealthResponse = (FinancialHealth);

export type FundamentalsGetDividendHistoryData = {
    /**
     * Number of years to retrieve
     */
    limit?: number;
    tradingCode: string;
};

export type FundamentalsGetDividendHistoryResponse = (Array<DividendHistory>);

export type FundamentalsGetHistoricalRatiosData = {
    tradingCode: string;
    /**
     * Number of years of history
     */
    years?: number;
};

export type FundamentalsGetHistoricalRatiosResponse = (HistoricalRatios);

export type FundamentalsCompareCompaniesData = {
    /**
     * Comma-separated trading codes (e.g., 'BATBC,SQURPHARMA,OLYMPIC')
     */
    codes: string;
};

export type FundamentalsCompareCompaniesResponse = (Array<CompanyComparison>);

export type FundamentalsSearchCompaniesData = {
    /**
     * Filter by category (A, B, G, N, Z)
     */
    category?: (string | null);
    /**
     * Maximum results to return
     */
    limit?: number;
    /**
     * Maximum P/E ratio
     */
    maxPe?: (number | string | null);
    /**
     * Minimum dividend yield %
     */
    minDividendYield?: (number | string | null);
    /**
     * Minimum P/E ratio
     */
    minPe?: (number | string | null);
    /**
     * Filter by sector (e.g., 'Food & Allied')
     */
    sector?: (string | null);
};

export type FundamentalsSearchCompaniesResponse = (Array<CompanySearchResult>);

export type FundamentalsCheckDataAvailabilityData = {
    tradingCode: string;
};

export type FundamentalsCheckDataAvailabilityResponse = (FundamentalDataAvailability);

export type FundsGetFundsSummaryResponse = (unknown);

export type FundsListTransactionsData = {
    limit?: number;
    offset?: number;
};

export type FundsListTransactionsResponse = (Array<AccountTransactionPublic>);

export type FundsDepositFundsData = {
    requestBody: FundsChangeRequest;
};

export type FundsDepositFundsResponse = (unknown);

export type FundsWithdrawFundsData = {
    requestBody: FundsChangeRequest;
};

export type FundsWithdrawFundsResponse = (unknown);

export type FundsUpdateFundsSettingsData = {
    requestBody: FundsSettingsRequest;
};

export type FundsUpdateFundsSettingsResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type KycGetKycInformationResponse = (KYCInformationPublic);

export type KycUpdateKycInformationData = {
    requestBody: KYCInformationUpdate;
};

export type KycUpdateKycInformationResponse = (KYCInformationPublic);

export type KycCreateKycInformationData = {
    requestBody: KYCInformationCreate;
};

export type KycCreateKycInformationResponse = (KYCInformationPublic);

export type KycGetKycStatusResponse = (unknown);

export type KycGetInvestmentGoalsResponse = (Array<UserInvestmentGoalPublic>);

export type KycCreateInvestmentGoalData = {
    requestBody: UserInvestmentGoalCreate;
};

export type KycCreateInvestmentGoalResponse = (UserInvestmentGoalPublic);

export type KycUpdateInvestmentGoalData = {
    goalId: string;
    requestBody: UserInvestmentGoalUpdate;
};

export type KycUpdateInvestmentGoalResponse = (UserInvestmentGoalPublic);

export type KycDeleteInvestmentGoalData = {
    goalId: string;
};

export type KycDeleteInvestmentGoalResponse = (unknown);

export type KycCreateGoalContributionData = {
    goalId: string;
    requestBody: UserInvestmentGoalContributionCreate;
};

export type KycCreateGoalContributionResponse = (UserInvestmentGoalContributionPublic);

export type KycListGoalContributionsData = {
    goalId: string;
};

export type KycListGoalContributionsResponse = (Array<UserInvestmentGoalContributionPublic>);

export type KycDeleteGoalContributionData = {
    contributionId: string;
};

export type KycDeleteGoalContributionResponse = (unknown);

export type KycGetUserAccountsResponse = (Array<UserAccountPublic>);

export type KycCreateUserAccountData = {
    requestBody: UserAccountCreate;
};

export type KycCreateUserAccountResponse = (UserAccountPublic);

export type KycUpdateUserAccountData = {
    accountId: string;
    requestBody: UserAccountUpdate;
};

export type KycUpdateUserAccountResponse = (UserAccountPublic);

export type KycDeleteUserAccountData = {
    accountId: string;
};

export type KycDeleteUserAccountResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MarketGetMarketSummaryResponse = ({
    [key: string]: unknown;
});

export type MarketListStocksData = {
    limit?: number;
    offset?: number;
    /**
     * Search by symbol or company name
     */
    q?: (string | null);
    sector?: (string | null);
};

export type MarketListStocksResponse = (Array<{
    [key: string]: unknown;
}>);

export type MarketGetStockData = {
    symbol: string;
};

export type MarketGetStockResponse = ({
    [key: string]: unknown;
});

export type MarketGetChartDataData = {
    symbol: string;
    /**
     * 1D (intraday ticks), 1W, 1M, 3M, 6M, 1Y, 2Y, 5Y, ALL for daily OHLC
     */
    timeframe?: string;
};

export type MarketGetChartDataResponse = ({
    [key: string]: unknown;
});

export type MarketGetTopMoversData = {
    limit?: number;
};

export type MarketGetTopMoversResponse = ({
    [key: string]: Array<{
        [key: string]: unknown;
    }>;
});

export type MarketGetMostActiveData = {
    limit?: number;
};

export type MarketGetMostActiveResponse = (Array<{
    [key: string]: unknown;
}>);

export type MarketGetIndicesData = {
    days?: number;
};

export type MarketGetIndicesResponse = ({
    [key: string]: unknown;
});

export type MarketGetTurnoverCompareResponse = ({
    [key: string]: unknown;
});

export type MarketGetMarketFlowsResponse = ({
    [key: string]: unknown;
});

export type MarketGetMacroSnapshotResponse = ({
    [key: string]: unknown;
});

export type MarketGetUpcomingEventsData = {
    limit?: number;
};

export type MarketGetUpcomingEventsResponse = ({
    [key: string]: unknown;
});

export type NewsListNewsData = {
    category?: (string | null);
    days?: number;
    limit?: number;
    offset?: number;
};

export type NewsListNewsResponse = (Array<NewsPublic>);

export type NewsCreateNewsData = {
    requestBody: NewsCreate;
};

export type NewsCreateNewsResponse = (NewsPublic);

export type NewsGetStockNewsData = {
    days?: number;
    symbol: string;
};

export type NewsGetStockNewsResponse = (Array<NewsPublic>);

export type OrdersCreateOrderData = {
    requestBody: OrderCreate;
};

export type OrdersCreateOrderResponse = (OrderPublic);

export type OrdersGetUserOrdersData = {
    portfolioId?: (string | null);
    status?: (OrderStatus | null);
};

export type OrdersGetUserOrdersResponse = (Array<OrderPublic>);

export type OrdersGetUserOrdersWithDetailsData = {
    portfolioId?: (string | null);
    status?: (OrderStatus | null);
};

export type OrdersGetUserOrdersWithDetailsResponse = (Array<OrderWithDetails>);

export type OrdersGetOrderData = {
    orderId: string;
};

export type OrdersGetOrderResponse = (OrderPublic);

export type OrdersUpdateOrderData = {
    orderId: string;
    requestBody: OrderUpdate;
};

export type OrdersUpdateOrderResponse = (OrderPublic);

export type OrdersCancelOrderData = {
    orderId: string;
};

export type OrdersCancelOrderResponse = (unknown);

export type OrdersGetOrderExecutionsData = {
    orderId: string;
};

export type OrdersGetOrderExecutionsResponse = (Array<OrderExecutionPublic>);

export type OrdersGetOrderSummaryData = {
    portfolioId?: (string | null);
};

export type OrdersGetOrderSummaryResponse = (OrderSummary);

export type PortfolioGetUserPortfoliosResponse = (Array<PortfolioPublic>);

export type PortfolioCreatePortfolioData = {
    requestBody: PortfolioCreate;
};

export type PortfolioCreatePortfolioResponse = (PortfolioPublic);

export type PortfolioGetPortfolioData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioResponse = (PortfolioPublic);

export type PortfolioUpdatePortfolioData = {
    portfolioId: string;
    requestBody: PortfolioUpdate;
};

export type PortfolioUpdatePortfolioResponse = (PortfolioPublic);

export type PortfolioDeletePortfolioData = {
    portfolioId: string;
};

export type PortfolioDeletePortfolioResponse = (unknown);

export type PortfolioAddPositionData = {
    averagePrice: number;
    portfolioId: string;
    quantity: number;
    stockSymbol: string;
};

export type PortfolioAddPositionResponse = (PortfolioPositionPublic);

export type PortfolioGetPortfolioPositionsData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioPositionsResponse = (Array<PortfolioPositionPublic>);

export type PortfolioGetPortfolioPositionsWithDetailsData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioPositionsWithDetailsResponse = (unknown);

export type PortfolioUpdatePositionData = {
    averagePrice?: (number | null);
    portfolioId: string;
    positionId: string;
    quantity?: (number | null);
};

export type PortfolioUpdatePositionResponse = (unknown);

export type PortfolioRemovePositionData = {
    portfolioId: string;
    positionId: string;
};

export type PortfolioRemovePositionResponse = (unknown);

export type PortfolioAddTradeData = {
    portfolioId: string;
    requestBody: TradeCreate;
};

export type PortfolioAddTradeResponse = (TradePublic);

export type PortfolioGetPortfolioTradesData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioTradesResponse = (Array<TradePublic>);

export type PortfolioUpdateTradeData = {
    portfolioId: string;
    requestBody: TradeUpdate;
    tradeId: string;
};

export type PortfolioUpdateTradeResponse = (TradePublic);

export type PortfolioDeleteTradeData = {
    portfolioId: string;
    tradeId: string;
};

export type PortfolioDeleteTradeResponse = (unknown);

export type PortfolioGetPortfolioSummaryData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioSummaryResponse = (PortfolioSummary);

export type PortfolioGetRecentTradesData = {
    limit?: number;
};

export type PortfolioGetRecentTradesResponse = (Array<TradeWithDetails>);

export type PortfolioGetOrdersTradesSummaryResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ResearchStockScreenerData = {
    /**
     * Maximum number of results
     */
    limit?: number;
    /**
     * Sector filter
     */
    sector?: (string | null);
    /**
     * Industry filter
     */
    industry?: (string | null);
    /**
     * Maximum dividend yield %
     */
    maxDividendYield?: (number | null);
    /**
     * Maximum market cap in millions
     */
    maxMarketCap?: (number | null);
    /**
     * Maximum P/E ratio
     */
    maxPeRatio?: (number | null);
    /**
     * Maximum stock price
     */
    maxPrice?: (number | null);
    /**
     * Maximum price-to-book ratio
     */
    maxPriceToBook?: (number | null);
    /**
     * Minimum dividend yield %
     */
    minDividendYield?: (number | null);
    /**
     * Minimum market cap in millions
     */
    minMarketCap?: (number | null);
    /**
     * Minimum P/E ratio
     */
    minPeRatio?: (number | null);
    /**
     * Minimum stock price
     */
    minPrice?: (number | null);
    /**
     * Minimum price-to-book ratio
     */
    minPriceToBook?: (number | null);
    /**
     * Minimum RSI value
     */
    minRsi?: (number | null);
    /**
     * Minimum average volume
     */
    minVolume?: (number | null);
    /**
     * Maximum RSI value
     */
    maxRsi?: (number | null);
    /**
     * Minimum daily price change percent
     */
    minPriceChange?: (number | null);
    /**
     * Maximum daily price change percent
     */
    maxPriceChange?: (number | null);
    /**
     * Moving average position filter (all, above_20, above_50, below_20, below_50)
     */
    movingAverage?: (string | null);
};

export type ResearchStockScreenerResponse = {
    total_results: number;
    filters_applied: Record<string, unknown>;
    stocks: Array<{
        stock_id: string;
        symbol: string;
        name: string;
        sector: (string | null);
        industry: (string | null);
        current_price: (number | null);
        change: (number | null);
        change_percent: (number | null);
        volume: (number | null);
        market_cap: (number | null);
        pe_ratio: (number | null);
        pb_ratio: (number | null);
        dividend_yield: (number | null);
        rsi: (number | null);
        sma_20: (number | null);
        sma_50: (number | null);
        rating: ('Strong Buy' | 'Buy' | 'Hold' | 'Sell' | 'Strong Sell');
    }>;
};

export type ResearchGetFundamentalAnalysisData = {
    symbol: string;
};

export type ResearchGetFundamentalAnalysisResponse = (unknown);

export type ResearchGetTechnicalAnalysisData = {
    /**
     * Number of days for analysis
     */
    period?: number;
    symbol: string;
};

export type ResearchGetTechnicalAnalysisResponse = (unknown);

export type ResearchGetStockNewsData = {
    /**
     * Number of news articles to return
     */
    limit?: number;
    symbol: string;
};

export type ResearchGetStockNewsResponse = (unknown);

export type ResearchGetSectorAnalysisResponse = (unknown);

export type ResearchGetStockOfTheDayResponse = (unknown);

export type ResearchGetAnalystPicksData = {
    limit?: number;
};

export type ResearchGetAnalystPicksResponse = (unknown);

export type ResearchGetEarningsHighlightsData = {
    limit?: number;
};

export type ResearchGetEarningsHighlightsResponse = (unknown);

export type ResearchGetThematicIdeasResponse = (unknown);

export type RiskManagementGetUserRiskProfileResponse = (UserRiskProfilePublic);

export type RiskManagementCreateUserRiskProfileData = {
    requestBody: UserRiskProfileCreate;
};

export type RiskManagementCreateUserRiskProfileResponse = (UserRiskProfilePublic);

export type RiskManagementGetRiskAlertsData = {
    isActive?: (boolean | null);
    portfolioId?: (string | null);
};

export type RiskManagementGetRiskAlertsResponse = (Array<RiskAlertPublic>);

export type RiskManagementCreateStockScreenerData = {
    requestBody: StockScreenerCreate;
};

export type RiskManagementCreateStockScreenerResponse = (StockScreenerPublic);

export type RiskManagementGetStockScreenersData = {
    isActive?: (boolean | null);
};

export type RiskManagementGetStockScreenersResponse = (Array<StockScreenerPublic>);

export type SubscriptionsListPlansResponse = (Array<SubscriptionPlanPublic>);

export type SubscriptionsCreatePlanData = {
    requestBody: SubscriptionPlanCreate;
};

export type SubscriptionsCreatePlanResponse = (SubscriptionPlanPublic);

export type SubscriptionsSubscribeData = {
    requestBody: UserSubscriptionCreate;
};

export type SubscriptionsSubscribeResponse = (UserSubscriptionPublic);

export type SubscriptionsStatusCheckResponse = (SubscriptionStatus);

export type SubscriptionsBkashPaymentData = {
    requestBody: PaymentRequest;
};

export type SubscriptionsBkashPaymentResponse = (PaymentResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WatchlistGetUserWatchlistsResponse = (Array<WatchlistPublic>);

export type WatchlistCreateWatchlistData = {
    requestBody: WatchlistCreate;
};

export type WatchlistCreateWatchlistResponse = (WatchlistPublic);

export type WatchlistGetWatchlistData = {
    watchlistId: string;
};

export type WatchlistGetWatchlistResponse = (WatchlistPublic);

export type WatchlistUpdateWatchlistData = {
    requestBody: WatchlistUpdate;
    watchlistId: string;
};

export type WatchlistUpdateWatchlistResponse = (WatchlistPublic);

export type WatchlistDeleteWatchlistData = {
    watchlistId: string;
};

export type WatchlistDeleteWatchlistResponse = (unknown);

export type WatchlistAddWatchlistItemData = {
    requestBody: WatchlistItemCreate;
    watchlistId: string;
};

export type WatchlistAddWatchlistItemResponse = (WatchlistItemPublic);

export type WatchlistGetWatchlistItemsData = {
    watchlistId: string;
};

export type WatchlistGetWatchlistItemsResponse = (Array<WatchlistItemPublic>);

export type WatchlistUpdateWatchlistItemData = {
    itemId: string;
    notes?: (string | null);
    watchlistId: string;
};

export type WatchlistUpdateWatchlistItemResponse = (WatchlistItemPublic);

export type WatchlistRemoveWatchlistItemData = {
    itemId: string;
    watchlistId: string;
};

export type WatchlistRemoveWatchlistItemResponse = (unknown);

export type WatchlistAddMultipleStocksData = {
    requestBody: Array<(string)>;
    watchlistId: string;
};

export type WatchlistAddMultipleStocksResponse = (unknown);

export type WatchlistRemoveMultipleStocksData = {
    requestBody: BulkRemoveRequest;
    watchlistId: string;
};

export type WatchlistRemoveMultipleStocksResponse = (unknown);

export type WatchlistAddMultipleBySymbolsData = {
    requestBody: BulkSymbolsRequest;
    watchlistId: string;
};

export type WatchlistAddMultipleBySymbolsResponse = (unknown);

export type WatchlistSearchStocksData = {
    limit?: number;
    query: string;
};

export type WatchlistSearchStocksResponse = (unknown);

export type WatchlistGetWatchlistItemsWithDetailsData = {
    watchlistId: string;
};

export type WatchlistGetWatchlistItemsWithDetailsResponse = (unknown);