// This file is auto-generated by @hey-api/openapi-ts

export type AccountTransactionPublic = {
    id: string;
    type: TransactionType;
    amount: string;
    currency: string;
    description: (string | null);
    created_at: string;
    portfolio_id: (string | null);
    order_id: (string | null);
    trade_id: (string | null);
};

/**
 * Types of investment accounts
 */
export type AccountType = 'INDIVIDUAL' | 'JOINT' | 'RETIREMENT_401K' | 'RETIREMENT_IRA' | 'RETIREMENT_ROTH_IRA' | 'TRUST' | 'CORPORATE';

export type AlertCreate = {
    alert_type: string;
    condition: string;
    target_value: (number | string);
    notification_method: string;
    is_recurring?: boolean;
    frequency?: (string | null);
    notes?: (string | null);
    stock_id?: (string | null);
};

export type AlertPublic = {
    alert_type: string;
    condition: string;
    target_value: string;
    notification_method: string;
    is_recurring?: boolean;
    frequency?: (string | null);
    notes?: (string | null);
    id: string;
    user_id: string;
    stock_id: (string | null);
    current_value: (string | null);
    status: string;
    last_triggered: (string | null);
    trigger_count: number;
    created_at: string;
    updated_at: string;
};

export type AlertUpdate = {
    alert_type?: (string | null);
    condition?: (string | null);
    target_value?: (number | string | null);
    notification_method?: (string | null);
    is_recurring?: (boolean | null);
    frequency?: (string | null);
    status?: (string | null);
    notes?: (string | null);
};

export type AllocationTargetCreate = {
    category: string;
    category_type?: string;
    target_percent: (number | string);
    min_percent?: (number | string | null);
    max_percent?: (number | string | null);
};

export type AllocationTargetPublic = {
    category: string;
    category_type?: string;
    target_percent: string;
    min_percent?: (string | null);
    max_percent?: (string | null);
    id: string;
    user_id: string;
    portfolio_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Annual earnings summary
 */
export type AnnualEarnings = {
    prev_year_eps?: (string | null);
    current_year_eps?: (string | null);
    growth_percent?: (string | null);
    profit_million?: (string | null);
};

/**
 * Asset allocation recommendation for a goal
 */
export type AssetAllocationRecommendation = {
    equity_percent: number;
    debt_percent: number;
    gold_percent: number;
    cash_percent: number;
    rationale: string;
    risk_level: RiskAppetite;
};

/**
 * Attribution analysis API response
 */
export type AttributionResponse = {
    portfolio_id: string;
    period: string;
    attribution: Array<{
        [key: string]: unknown;
    }>;
    total_attribution?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Benchmark comparison for a single period
 */
export type BenchmarkComparisonPeriod = {
    period: string;
    portfolio_return: number;
    benchmark_return: number;
    relative_return: number;
    alpha?: (number | null);
    beta?: (number | null);
    tracking_error?: (number | null);
    information_ratio?: (number | null);
};

/**
 * Benchmark comparison API response
 */
export type BenchmarkComparisonResponse = {
    portfolio_id: string;
    benchmark_id: string;
    benchmark_name: string;
    comparison: Array<BenchmarkComparisonPeriod>;
};

/**
 * List of available benchmarks
 */
export type BenchmarkListResponse = {
    benchmarks: Array<BenchmarkPublic>;
};

/**
 * Public benchmark model for API responses
 */
export type BenchmarkPublic = {
    name: string;
    ticker?: (string | null);
    description?: (string | null);
    asset_class?: (string | null);
    region?: (string | null);
    data_source?: (string | null);
    is_active?: boolean;
    id: string;
    created_at: string;
};

export type Body_analytics_upsert_allocation_targets = {
    targets: Array<AllocationTargetCreate>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_portfolio_upload_portfolio_statement = {
    file: (Blob | File);
};

/**
 * Request model for bulk saving holdings
 */
export type BulkHoldingsSaveRequest = {
    client_info: ClientInfo;
    holdings: Array<HoldingItem_Input>;
    total_portfolio_value: (number | string);
    total_unrealized_gain_loss: (number | string);
};

/**
 * Response model after saving holdings
 */
export type BulkHoldingsSaveResponse = {
    success: boolean;
    message: string;
    /**
     * Number of holdings added
     */
    added_count?: number;
    /**
     * Number of holdings updated
     */
    updated_count?: number;
    portfolio_id: string;
    /**
     * Any warnings during save
     */
    warnings?: Array<(string)>;
};

export type BulkRemoveRequest = {
    item_ids?: (Array<(string)> | null);
    stock_ids?: (Array<(string)> | null);
};

export type BulkSymbolsRequest = {
    symbols: Array<(string)>;
};

/**
 * Client information from portfolio statement
 */
export type ClientInfo = {
    /**
     * Client code from the statement
     */
    client_code: string;
    /**
     * Beneficiary Owner ID
     */
    bo_id?: (string | null);
    /**
     * Account name or type
     */
    name: string;
    /**
     * Statement date
     */
    statement_date: string;
    /**
     * Account type (CASH, MARGIN, etc.)
     */
    account_type?: string;
};

/**
 * Company basic information for fundamental analysis
 */
export type CompanyBasicInfo = {
    trading_code: string;
    company_name?: (string | null);
    category?: (string | null);
    sector?: (string | null);
    listing_year?: (number | null);
    head_office?: (string | null);
    factory?: (string | null);
    contact: ContactInfo;
    website?: (string | null);
};

/**
 * Company comparison metrics
 */
export type CompanyComparison = {
    trading_code: string;
    company_name?: (string | null);
    /**
     * Last Trading Price
     */
    ltp?: (string | null);
    /**
     * P/E ratio
     */
    pe?: (string | null);
    /**
     * Dividend yield %
     */
    dividend_yield?: (string | null);
    /**
     * Net Asset Value
     */
    nav?: (string | null);
    /**
     * Market cap in millions
     */
    market_cap?: (string | null);
    /**
     * Earnings per share
     */
    eps?: (string | null);
    sector?: (string | null);
};

/**
 * Search result item
 */
export type CompanySearchResult = {
    trading_code: string;
    company_name?: (string | null);
    sector?: (string | null);
    category?: (string | null);
    /**
     * Last Trading Price
     */
    ltp?: (string | null);
    pe_ratio?: (string | null);
    market_cap?: (string | null);
};

/**
 * Company contact information
 */
export type ContactInfo = {
    company_secretary?: (string | null);
    email?: (string | null);
    cell?: (string | null);
};

/**
 * Annual dividend information
 */
export type DividendHistory = {
    year: number;
    /**
     * Cash dividend %
     */
    cash_dividend?: (string | null);
    /**
     * Stock dividend %
     */
    stock_dividend?: (string | null);
    /**
     * Dividend yield %
     */
    dividend_yield?: (string | null);
};

/**
 * Complete earnings and profit response
 */
export type EarningsProfitResponse = {
    quarters?: Array<QuarterlyEarnings>;
    annual?: (AnnualEarnings | null);
};

/**
 * Financial health and loan status
 */
export type FinancialHealth = {
    /**
     * Short-term loan in millions
     */
    short_term_loan?: (string | null);
    /**
     * Long-term loan in millions
     */
    long_term_loan?: (string | null);
    /**
     * Total loan in millions
     */
    total_loan?: (string | null);
    /**
     * Reserve and surplus in millions
     */
    reserve_and_surplus?: (string | null);
    /**
     * Debt status description
     */
    debt_status?: string;
    /**
     * Additional remarks
     */
    remarks?: string;
};

/**
 * Data availability status for a company
 */
export type FundamentalDataAvailability = {
    has_basic_info?: boolean;
    has_financial_data?: boolean;
    has_dividend_data?: boolean;
    has_shareholding_data?: boolean;
    has_loan_data?: boolean;
    has_quarterly_data?: boolean;
    latest_data_year?: (number | null);
    latest_quarter_date?: (string | null);
};

export type FundsChangeRequest = {
    amount: number;
    portfolio_id?: (string | null);
    description?: (string | null);
};

export type FundsSettingsRequest = {
    credit_limit: number;
};

/**
 * Goal-related alert
 */
export type GoalAlert = {
    alert_type: string;
    severity: string;
    message: string;
    action_required?: (string | null);
    created_at: string;
};

/**
 * List of alerts for a goal
 */
export type GoalAlertResponse = {
    goal_id: string;
    alerts: Array<GoalAlert>;
    total_alerts: number;
};

/**
 * Detailed goal progress information
 */
export type GoalProgressResponse = {
    goal_id: string;
    goal_name: string;
    current_value: number;
    target_amount: number;
    progress_percentage: number;
    on_track_status: GoalTrackingStatus;
    shortfall_amount: number;
    total_contributions: number;
    total_returns: number;
    months_remaining: number;
    projected_final_value: number;
    recommended_action?: (string | null);
};

/**
 * Goal progress tracking status
 */
export type GoalTrackingStatus = 'ON_TRACK' | 'BEHIND' | 'AHEAD' | 'AT_RISK';

/**
 * Historical financial ratios for charting
 */
export type HistoricalRatios = {
    /**
     * Historical EPS values
     */
    eps_history?: Array<(string | null)>;
    /**
     * Historical P/E ratios
     */
    pe_history?: Array<(string | null)>;
    /**
     * Historical NAV values
     */
    nav_history?: Array<(string | null)>;
    /**
     * Historical profit in millions
     */
    profit_history?: Array<(string | null)>;
    /**
     * Years for the data points
     */
    years?: Array<(number)>;
};

/**
 * Individual holding/position from statement
 */
export type HoldingItem_Input = {
    /**
     * Stock trading code/symbol from database
     */
    symbol: string;
    /**
     * Company name
     */
    company_name: string;
    /**
     * Number of shares
     */
    quantity: number;
    /**
     * Average cost price per share
     */
    cost_price: (number | string);
    /**
     * Current market price per share
     */
    market_price: (number | string);
    /**
     * Current market value of position
     */
    market_value: (number | string);
    /**
     * Unrealized profit/loss
     */
    unrealized_gain_loss: (number | string);
    /**
     * Unrealized profit/loss percentage
     */
    unrealized_gain_loss_percent: (number | string);
};

/**
 * Individual holding/position from statement
 */
export type HoldingItem_Output = {
    /**
     * Stock trading code/symbol from database
     */
    symbol: string;
    /**
     * Company name
     */
    company_name: string;
    /**
     * Number of shares
     */
    quantity: number;
    /**
     * Average cost price per share
     */
    cost_price: string;
    /**
     * Current market price per share
     */
    market_price: string;
    /**
     * Current market value of position
     */
    market_value: string;
    /**
     * Unrealized profit/loss
     */
    unrealized_gain_loss: string;
    /**
     * Unrealized profit/loss percentage
     */
    unrealized_gain_loss_percent: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Investment objectives
 */
export type InvestmentGoal = 'RETIREMENT' | 'EDUCATION' | 'WEALTH_BUILDING' | 'INCOME_GENERATION' | 'CAPITAL_PRESERVATION' | 'SHORT_TERM_GAINS' | 'HOME_PURCHASE' | 'VACATION' | 'EMERGENCY_FUND' | 'WEDDING' | 'VEHICLE_PURCHASE' | 'BUSINESS_STARTUP';

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type KYCInformationCreate = {
    first_name: string;
    last_name: string;
    date_of_birth: string;
    ssn_last_four: string;
    phone_number: string;
    street_address: string;
    city: string;
    state: string;
    zip_code: string;
    country?: string;
    employer_name?: (string | null);
    occupation?: (string | null);
    annual_income?: (number | null);
    employment_status?: (string | null);
    net_worth?: (number | null);
    liquid_net_worth?: (number | null);
    investment_experience?: (string | null);
};

export type KYCInformationPublic = {
    first_name: string;
    last_name: string;
    date_of_birth: string;
    ssn_last_four: string;
    phone_number: string;
    street_address: string;
    city: string;
    state: string;
    zip_code: string;
    country?: string;
    employer_name?: (string | null);
    occupation?: (string | null);
    annual_income?: (number | null);
    employment_status?: (string | null);
    net_worth?: (number | null);
    liquid_net_worth?: (number | null);
    investment_experience?: (string | null);
    id: string;
    kyc_status: KYCStatus;
    verification_date?: (string | null);
    created_at: string;
    updated_at: string;
};

export type KYCInformationUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    date_of_birth?: (string | null);
    phone_number?: (string | null);
    street_address?: (string | null);
    city?: (string | null);
    state?: (string | null);
    zip_code?: (string | null);
    country?: (string | null);
    employer_name?: (string | null);
    occupation?: (string | null);
    annual_income?: (number | null);
    employment_status?: (string | null);
    net_worth?: (number | null);
    liquid_net_worth?: (number | null);
    investment_experience?: (string | null);
};

/**
 * KYC verification status
 */
export type KYCStatus = 'PENDING' | 'IN_REVIEW' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';

/**
 * Market summary and valuation metrics
 */
export type MarketSummary = {
    /**
     * Last Trading Price
     */
    ltp?: (string | null);
    /**
     * Price change
     */
    ltp_change?: (string | null);
    /**
     * Yesterday's Closing Price
     */
    ycp?: (string | null);
    /**
     * Current P/E ratio
     */
    current_pe?: (string | null);
    /**
     * Audited P/E ratio
     */
    audited_pe?: (string | null);
    /**
     * Dividend yield %
     */
    dividend_yield?: (string | null);
    /**
     * Net Asset Value per share
     */
    nav?: (string | null);
    /**
     * Face value per share
     */
    face_value?: (string | null);
    /**
     * Market capitalization in millions
     */
    market_cap?: (string | null);
    /**
     * Paid-up capital in millions
     */
    paid_up_capital?: (string | null);
    /**
     * Authorized capital in millions
     */
    authorized_capital?: (string | null);
    /**
     * Reserve and surplus in millions
     */
    reserve_and_surplus?: (string | null);
    /**
     * Financial year end date
     */
    year_end?: (string | null);
    /**
     * Last AGM date
     */
    last_agm?: (string | null);
    week_52_range: Week52Range;
};

export type Message = {
    message: string;
};

/**
 * Monthly return data
 */
export type MonthlyReturn = {
    month: string;
    month_number: number;
    return_value: number;
    portfolio_value_start: number;
    portfolio_value_end: number;
    benchmark_return?: (number | null);
};

/**
 * Monthly returns API response
 */
export type MonthlyReturnsResponse = {
    portfolio_id: string;
    year: number;
    monthly_returns: Array<MonthlyReturn>;
    ytd_return: number;
    best_month?: ({
    [key: string]: unknown;
} | null);
    worst_month?: ({
    [key: string]: unknown;
} | null);
    positive_months: number;
    negative_months: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NewsCreate = {
    title: string;
    content: string;
    summary?: (string | null);
    source: string;
    source_url?: (string | null);
    author?: (string | null);
    category: string;
    tags?: Array<(string)>;
    sentiment?: (string | null);
    sentiment_score?: (number | string | null);
    published_at: string;
    is_active?: boolean;
};

export type NewsPublic = {
    title: string;
    content: string;
    summary?: (string | null);
    source: string;
    source_url?: (string | null);
    author?: (string | null);
    category: string;
    tags?: Array<(string)>;
    sentiment?: (string | null);
    sentiment_score?: (string | null);
    published_at: string;
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type OrderCreate = {
    order_type: OrderType;
    side: OrderSide;
    quantity: number;
    price?: (number | string | null);
    stop_price?: (number | string | null);
    validity?: OrderValidity;
    notes?: (string | null);
    is_simulated?: boolean;
    stock_id: string;
    portfolio_id?: (string | null);
};

export type OrderExecutionPublic = {
    quantity: number;
    price: string;
    amount: string;
    commission: string;
    net_amount: string;
    executed_at: string;
    exchange_trade_id: (string | null);
    id: string;
    order_id: string;
};

export type OrderPublic = {
    order_type: OrderType;
    side: OrderSide;
    quantity: number;
    price?: (string | null);
    stop_price?: (string | null);
    validity?: OrderValidity;
    notes?: (string | null);
    is_simulated?: boolean;
    id: string;
    user_id: string;
    portfolio_id: (string | null);
    stock_id: string;
    status: OrderStatus;
    filled_quantity: number;
    average_price: (string | null);
    total_amount: (string | null);
    commission: (string | null);
    net_amount: (string | null);
    placed_at: string;
    filled_at: (string | null);
    cancelled_at: (string | null);
    expires_at: (string | null);
    exchange_order_id: (string | null);
    rejection_reason: (string | null);
};

/**
 * Order side (buy/sell)
 */
export type OrderSide = 'BUY' | 'SELL';

/**
 * Order status
 */
export type OrderStatus = 'PENDING' | 'PARTIAL' | 'FILLED' | 'CANCELLED' | 'REJECTED' | 'EXPIRED' | 'PENDING_CANCEL';

export type OrderSummary = {
    total_orders: number;
    pending_orders: number;
    filled_orders: number;
    cancelled_orders: number;
    rejected_orders: number;
    total_volume: number;
    total_amount: string;
    orders: Array<OrderPublic>;
};

/**
 * Types of orders
 */
export type OrderType = 'MARKET' | 'LIMIT' | 'STOP' | 'STOP_LIMIT';

export type OrderUpdate = {
    price?: (number | string | null);
    stop_price?: (number | string | null);
    quantity?: (number | null);
    validity?: (OrderValidity | null);
    notes?: (string | null);
};

/**
 * Order validity period
 */
export type OrderValidity = 'DAY' | 'GTC' | 'IOC' | 'FOK';

/**
 * Public order payload with stock details for UI convenience
 */
export type OrderWithDetails = {
    order_type: OrderType;
    side: OrderSide;
    quantity: number;
    price?: (string | null);
    stop_price?: (string | null);
    validity?: OrderValidity;
    notes?: (string | null);
    is_simulated?: boolean;
    id: string;
    user_id: string;
    portfolio_id: (string | null);
    stock_id: string;
    status: OrderStatus;
    filled_quantity: number;
    average_price: (string | null);
    total_amount: (string | null);
    commission: (string | null);
    net_amount: (string | null);
    placed_at: string;
    filled_at: (string | null);
    cancelled_at: (string | null);
    expires_at: (string | null);
    exchange_order_id: (string | null);
    rejection_reason: (string | null);
    symbol: string;
    company_name: string;
};

export type PaymentRequest = {
    plan_id: string;
    payment_method: string;
    amount: (number | string);
    currency?: string;
};

export type PaymentResponse = {
    payment_id: string;
    transaction_id: string;
    status: string;
    gateway_url?: (string | null);
    gateway_data?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Performance summary response model
 */
export type PerformanceSummary = {
    total_value: number;
    total_cost: number;
    cumulative_return: number;
    cumulative_return_percent: number;
    time_weighted_return: number;
    money_weighted_return: number;
    annualized_return: number;
    sharpe_ratio?: (number | null);
    sortino_ratio?: (number | null);
    max_drawdown?: (number | null);
    volatility?: (number | null);
    best_month?: ({
    [key: string]: unknown;
} | null);
    worst_month?: ({
    [key: string]: unknown;
} | null);
    best_quarter?: ({
    [key: string]: unknown;
} | null);
    worst_quarter?: ({
    [key: string]: unknown;
} | null);
    net_contributions?: (number | null);
    net_withdrawals?: (number | null);
    inception_date?: (string | null);
    days_since_inception?: (number | null);
};

/**
 * Complete performance summary API response
 */
export type PerformanceSummaryResponse = {
    portfolio_id: string;
    portfolio_name: string;
    period: string;
    summary: PerformanceSummary;
};

export type PortfolioCreate = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
};

export type PortfolioPositionPublic = {
    quantity: number;
    average_price: string;
    total_investment: string;
    current_value: string;
    unrealized_pnl: string;
    unrealized_pnl_percent: string;
    id: string;
    portfolio_id: string;
    stock_id: string;
    last_updated: string;
};

export type PortfolioPublic = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
    cash_balance?: (string | null);
};

/**
 * Response model for parsed portfolio statement
 */
export type PortfolioStatementResponse = {
    client_info: ClientInfo;
    holdings?: Array<HoldingItem_Output>;
    /**
     * Total portfolio value
     */
    total_portfolio_value: string;
    /**
     * Total unrealized gain/loss
     */
    total_unrealized_gain_loss: string;
};

export type PortfolioSummary = {
    portfolio_id: string;
    portfolio_name: string;
    total_investment: string;
    current_value: string;
    unrealized_pnl: string;
    unrealized_pnl_percent: string;
    total_positions: number;
    positions: Array<PortfolioPositionPublic>;
};

export type PortfolioUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_default?: (boolean | null);
    is_active?: (boolean | null);
    cash_balance?: (number | string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Investment product recommendation
 */
export type ProductRecommendation = {
    product_type: string;
    product_name: string;
    ticker?: (string | null);
    allocation_percent: number;
    expected_return: number;
    risk_level: string;
    rationale: string;
};

/**
 * List of product recommendations for a goal
 */
export type ProductRecommendationResponse = {
    goal_id: string;
    recommendations: Array<ProductRecommendation>;
    total_allocation: number;
    diversification_score: number;
};

/**
 * Quarterly earnings data
 */
export type QuarterlyEarnings = {
    quarter: string;
    prev_year_eps?: (string | null);
    current_year_eps?: (string | null);
    growth_percent?: (string | null);
    period: string;
};

/**
 * Request to execute rebalancing
 */
export type RebalancingExecuteRequest = {
    suggestions: Array<{
        [key: string]: unknown;
    }>;
    simulate?: boolean;
};

/**
 * Response after executing rebalancing
 */
export type RebalancingExecuteResponse = {
    run_id: string;
    executed_at: string;
    trades: Array<RebalancingTradePublic>;
    buy_value: string;
    sell_value: string;
    transaction_cost: string;
    drift_before: string;
    drift_after: string;
};

/**
 * Response for history endpoint
 */
export type RebalancingHistoryResponse = {
    portfolio_id: string;
    runs: Array<RebalancingRunPublic>;
    total_runs: number;
};

/**
 * Public rebalancing run info
 */
export type RebalancingRunPublic = {
    id: string;
    portfolio_id: string;
    type: string;
    drift_before: string;
    drift_after: string;
    trades_count: number;
    buy_value: string;
    sell_value: string;
    transaction_cost: string;
    notes: (string | null);
    executed_at: string;
    trades?: Array<RebalancingTradePublic>;
};

export type RebalancingSettingsPublic = {
    enabled?: boolean;
    threshold_pct?: string;
    frequency?: string;
    min_trade_value?: string;
    id: string;
    user_id: string;
    portfolio_id: string;
    last_rebalance_at?: (string | null);
    next_rebalance_at?: (string | null);
    created_at: string;
    updated_at: string;
};

export type RebalancingSettingsUpdate = {
    enabled?: (boolean | null);
    threshold_pct?: (number | string | null);
    frequency?: (string | null);
    min_trade_value?: (number | string | null);
};

/**
 * Single rebalancing suggestion
 */
export type RebalancingSuggestion = {
    symbol: string;
    company_name: string;
    sector: string;
    action: string;
    current_allocation: string;
    target_allocation: string;
    deviation: string;
    suggested_shares: number;
    suggested_value: string;
    current_value: string;
    priority: string;
};

/**
 * Response for suggestions endpoint
 */
export type RebalancingSuggestionsResponse = {
    portfolio_id: string;
    threshold_pct: string;
    min_trade_value: string;
    suggestions: Array<RebalancingSuggestion>;
    totals: {
        [key: string]: unknown;
    };
};

/**
 * Public trade info
 */
export type RebalancingTradePublic = {
    symbol: string;
    action: string;
    quantity: number;
    price: string;
    value: string;
};

export type RiskAlertPublic = {
    alert_type: string;
    severity: string;
    message: string;
    metric_value?: (string | null);
    threshold_value?: (string | null);
    is_active?: boolean;
    id: string;
    user_id: string;
    portfolio_id: (string | null);
    created_at: string;
    resolved_at: (string | null);
};

/**
 * Risk tolerance levels
 */
export type RiskAppetite = 'CONSERVATIVE' | 'MODERATE' | 'AGGRESSIVE';

/**
 * Risk metrics API response
 */
export type RiskMetricsResponse = {
    portfolio_id: string;
    period: string;
    risk_metrics: {
        [key: string]: unknown;
    };
};

/**
 * User risk profiles
 */
export type RiskProfile = 'CONSERVATIVE' | 'MODERATE' | 'AGGRESSIVE';

/**
 * Shareholding pattern changes
 */
export type ShareholdingChange = {
    foreign?: (string | null);
    public?: (string | null);
};

/**
 * Shareholding distribution
 */
export type ShareholdingPattern = {
    date: string;
    /**
     * Sponsor/Director %
     */
    director?: (string | null);
    /**
     * Government %
     */
    govt?: (string | null);
    /**
     * Institute %
     */
    institute?: (string | null);
    /**
     * Foreign %
     */
    foreign?: (string | null);
    /**
     * Public %
     */
    public?: (string | null);
    change?: (ShareholdingChange | null);
};

/**
 * SIP calculation response
 */
export type SIPCalculationResult = {
    monthly_sip_required: number;
    total_investment: number;
    expected_final_value: number;
    expected_returns: number;
    time_period_months: number;
    probability_of_success: number;
};

export type StockScreenerCreate = {
    name: string;
    description?: (string | null);
    criteria: {
        [key: string]: unknown;
    };
    is_active?: boolean;
};

export type StockScreenerPublic = {
    name: string;
    description?: (string | null);
    criteria: {
        [key: string]: unknown;
    };
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type SubscriptionPlanCreate = {
    name: string;
    description: string;
    price: (number | string);
    currency?: string;
    duration_days?: number;
    features?: {
        [key: string]: unknown;
    };
    is_active?: boolean;
};

export type SubscriptionPlanPublic = {
    name: string;
    description: string;
    price: string;
    currency?: string;
    duration_days?: number;
    features?: {
        [key: string]: unknown;
    };
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type SubscriptionStatus = {
    user_id: string;
    current_plan?: (string | null);
    status: string;
    start_date?: (string | null);
    end_date?: (string | null);
    is_active: boolean;
    features?: {
        [key: string]: unknown;
    };
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TradeCreate = {
    trade_type: string;
    quantity: number;
    price: (number | string);
    total_amount: (number | string);
    commission: (number | string);
    net_amount: (number | string);
    trade_date: string;
    notes?: (string | null);
    is_simulated?: boolean;
    stock_id: string;
    portfolio_id?: (string | null);
};

export type TradePublic = {
    trade_type: string;
    quantity: number;
    price: string;
    total_amount: string;
    commission: string;
    net_amount: string;
    trade_date: string;
    notes?: (string | null);
    is_simulated?: boolean;
    id: string;
    portfolio_id: (string | null);
    stock_id: string;
    created_at: string;
};

export type TradeUpdate = {
    trade_type?: (string | null);
    quantity?: (number | null);
    price?: (number | string | null);
    total_amount?: (number | string | null);
    commission?: (number | string | null);
    net_amount?: (number | string | null);
    trade_date?: (string | null);
    notes?: (string | null);
    is_simulated?: (boolean | null);
};

/**
 * Public trade payload with stock details for UI convenience
 */
export type TradeWithDetails = {
    trade_type: string;
    quantity: number;
    price: string;
    total_amount: string;
    commission: string;
    net_amount: string;
    trade_date: string;
    notes?: (string | null);
    is_simulated?: boolean;
    id: string;
    portfolio_id: (string | null);
    stock_id: string;
    created_at: string;
    symbol: string;
    company_name: string;
};

export type TransactionType = 'DEPOSIT' | 'WITHDRAWAL' | 'BUY' | 'SELL' | 'ORDER_PLACED' | 'ORDER_CANCELLED' | 'DIVIDEND' | 'FEE' | 'ADJUSTMENT';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserAccountCreate = {
    account_type: AccountType;
    account_name: string;
    account_number?: (string | null);
    joint_holder_name?: (string | null);
    joint_holder_ssn?: (string | null);
};

export type UserAccountPublic = {
    account_type: AccountType;
    account_name: string;
    account_number?: (string | null);
    joint_holder_name?: (string | null);
    joint_holder_ssn?: (string | null);
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type UserAccountUpdate = {
    account_name?: (string | null);
    account_number?: (string | null);
    is_active?: (boolean | null);
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Create a new goal contribution
 */
export type UserInvestmentGoalContributionCreate = {
    amount: number;
    contributed_at?: (string | null);
    notes?: (string | null);
};

/**
 * Public-facing contribution data
 */
export type UserInvestmentGoalContributionPublic = {
    amount: number;
    contributed_at: string;
    notes?: (string | null);
    id: string;
    goal_id: string;
    user_id: string;
    created_at: string;
};

/**
 * Create a new investment goal
 */
export type UserInvestmentGoalCreate = {
    goal_type: InvestmentGoal;
    target_amount?: (number | null);
    target_date?: (string | null);
    priority?: number;
    description?: (string | null);
    is_active?: boolean;
    current_savings?: (number | null);
    risk_appetite?: (RiskAppetite | null);
    current_monthly_sip?: (number | null);
    linked_portfolio_id?: (string | null);
    auto_rebalance_enabled?: boolean;
    rebalance_threshold?: (number | null);
};

/**
 * Public-facing investment goal data
 */
export type UserInvestmentGoalPublic = {
    goal_type: InvestmentGoal;
    target_amount?: (number | null);
    target_date?: (string | null);
    priority?: number;
    description?: (string | null);
    is_active?: boolean;
    current_savings?: (number | null);
    risk_appetite?: (RiskAppetite | null);
    current_monthly_sip?: (number | null);
    linked_portfolio_id?: (string | null);
    auto_rebalance_enabled?: boolean;
    rebalance_threshold?: (number | null);
    id: string;
    user_id: string;
    monthly_sip_required?: (number | null);
    equity_allocation?: (number | null);
    debt_allocation?: (number | null);
    gold_allocation?: (number | null);
    cash_allocation?: (number | null);
    expected_return_min?: (number | null);
    expected_return_max?: (number | null);
    expected_return_avg?: (number | null);
    probability_achievement?: (number | null);
    projected_final_value?: (number | null);
    current_value?: (number | null);
    total_contributions?: (number | null);
    total_returns?: (number | null);
    progress_percentage?: (number | null);
    on_track_status?: (GoalTrackingStatus | null);
    shortfall_amount?: (number | null);
    last_rebalance_date?: (string | null);
    next_rebalance_date?: (string | null);
    last_reviewed_date?: (string | null);
    milestones?: {
        [key: string]: unknown;
    };
    created_at: string;
    updated_at: string;
};

/**
 * Update an existing investment goal
 */
export type UserInvestmentGoalUpdate = {
    goal_type?: (InvestmentGoal | null);
    target_amount?: (number | null);
    target_date?: (string | null);
    priority?: (number | null);
    description?: (string | null);
    is_active?: (boolean | null);
    current_savings?: (number | null);
    risk_appetite?: (RiskAppetite | null);
    current_monthly_sip?: (number | null);
    linked_portfolio_id?: (string | null);
    auto_rebalance_enabled?: (boolean | null);
    rebalance_threshold?: (number | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRiskProfileCreate = {
    risk_profile?: RiskProfile;
    max_portfolio_volatility?: (number | string);
    max_single_position?: (number | string);
    max_sector_concentration?: (number | string);
    target_sharpe_ratio?: (number | string);
    max_drawdown_tolerance?: (number | string);
};

export type UserRiskProfilePublic = {
    risk_profile?: RiskProfile;
    max_portfolio_volatility?: string;
    max_single_position?: string;
    max_sector_concentration?: string;
    target_sharpe_ratio?: string;
    max_drawdown_tolerance?: string;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserSubscriptionCreate = {
    status: string;
    start_date: string;
    end_date: string;
    auto_renew?: boolean;
    plan_id: string;
};

export type UserSubscriptionPublic = {
    status: string;
    start_date: string;
    end_date: string;
    auto_renew?: boolean;
    id: string;
    user_id: string;
    plan_id: string;
    created_at: string;
    updated_at: string;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Single point in portfolio value history
 */
export type ValueHistoryPoint = {
    date: string;
    portfolio_value: number;
    portfolio_return?: (number | null);
    portfolio_cumulative_return?: (number | null);
    benchmark_value?: (number | null);
    benchmark_return?: (number | null);
    benchmark_cumulative_return?: (number | null);
    relative_return?: (number | null);
    alpha?: (number | null);
};

/**
 * Portfolio value history API response
 */
export type ValueHistoryResponse = {
    portfolio_id: string;
    benchmark_id?: (string | null);
    benchmark_name?: (string | null);
    frequency: string;
    data: Array<ValueHistoryPoint>;
};

export type WatchlistCreate = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
};

export type WatchlistItemCreate = {
    notes?: (string | null);
    stock_id: string;
};

export type WatchlistItemPublic = {
    notes?: (string | null);
    id: string;
    watchlist_id: string;
    stock_id: string;
    added_at: string;
};

export type WatchlistPublic = {
    name: string;
    description?: (string | null);
    is_default?: boolean;
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type WatchlistUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_default?: (boolean | null);
    is_active?: (boolean | null);
};

/**
 * 52-week price range
 */
export type Week52Range = {
    low?: (string | null);
    high?: (string | null);
};

/**
 * What-if scenario input parameters
 */
export type WhatIfScenarioRequest = {
    additional_monthly_investment?: (number | null);
    delay_months?: (number | null);
    return_adjustment?: (number | null);
};

/**
 * What-if scenario calculation results
 */
export type WhatIfScenarioResponse = {
    scenario_description: string;
    new_monthly_sip: number;
    new_projected_value: number;
    new_probability: number;
    impact_on_goal: string;
    recommendation: string;
};

export type AlertsListAlertsResponse = (Array<AlertPublic>);

export type AlertsCreateAlertData = {
    requestBody: AlertCreate;
};

export type AlertsCreateAlertResponse = (AlertPublic);

export type AlertsUpdateAlertData = {
    alertId: string;
    requestBody: AlertUpdate;
};

export type AlertsUpdateAlertResponse = (AlertPublic);

export type AlertsDeleteAlertData = {
    alertId: string;
};

export type AlertsDeleteAlertResponse = (void);

export type AlertsEvaluateAlertData = {
    alertId: string;
};

export type AlertsEvaluateAlertResponse = (AlertPublic);

export type AnalyticsGetPortfolioPerformanceData = {
    /**
     * Time period: 1D, 1W, 1M, 3M, 6M, 1Y, 2Y, 5Y, ALL
     */
    period?: string;
    portfolioId: string;
};

export type AnalyticsGetPortfolioPerformanceResponse = (unknown);

export type AnalyticsGetPortfolioAllocationData = {
    portfolioId: string;
};

export type AnalyticsGetPortfolioAllocationResponse = (unknown);

export type AnalyticsGetBenchmarkComparisonData = {
    /**
     * Benchmark symbol (e.g., SPY, QQQ, IWM)
     */
    benchmark?: string;
    /**
     * Time period: 1M, 3M, 6M, 1Y, 2Y, 5Y
     */
    period?: string;
    portfolioId: string;
};

export type AnalyticsGetBenchmarkComparisonResponse = (unknown);

export type AnalyticsGetDividendAnalysisData = {
    portfolioId: string;
};

export type AnalyticsGetDividendAnalysisResponse = (unknown);

export type AnalyticsGetCostBasisAnalysisData = {
    portfolioId: string;
};

export type AnalyticsGetCostBasisAnalysisResponse = (unknown);

export type AnalyticsGetMarketSentimentData = {
    days?: number;
};

export type AnalyticsGetMarketSentimentResponse = ({
    [key: string]: unknown;
});

export type AnalyticsGetAllocationTargetsData = {
    portfolioId: string;
};

export type AnalyticsGetAllocationTargetsResponse = (Array<AllocationTargetPublic>);

export type AnalyticsUpsertAllocationTargetsData = {
    portfolioId: string;
    requestBody: Body_analytics_upsert_allocation_targets;
};

export type AnalyticsUpsertAllocationTargetsResponse = (Array<AllocationTargetPublic>);

export type DashboardGetDashboardSummaryResponse = (unknown);

export type FundamentalsGetCompanyInfoData = {
    tradingCode: string;
};

export type FundamentalsGetCompanyInfoResponse = (CompanyBasicInfo);

export type FundamentalsGetMarketSummaryData = {
    tradingCode: string;
};

export type FundamentalsGetMarketSummaryResponse = (MarketSummary);

export type FundamentalsGetShareholdingPatternData = {
    tradingCode: string;
};

export type FundamentalsGetShareholdingPatternResponse = (ShareholdingPattern);

export type FundamentalsGetEarningsProfitData = {
    tradingCode: string;
};

export type FundamentalsGetEarningsProfitResponse = (EarningsProfitResponse);

export type FundamentalsGetFinancialHealthData = {
    tradingCode: string;
};

export type FundamentalsGetFinancialHealthResponse = (FinancialHealth);

export type FundamentalsGetDividendHistoryData = {
    /**
     * Number of years to retrieve
     */
    limit?: number;
    tradingCode: string;
};

export type FundamentalsGetDividendHistoryResponse = (Array<DividendHistory>);

export type FundamentalsGetHistoricalRatiosData = {
    tradingCode: string;
    /**
     * Number of years of history
     */
    years?: number;
};

export type FundamentalsGetHistoricalRatiosResponse = (HistoricalRatios);

export type FundamentalsCompareCompaniesData = {
    /**
     * Comma-separated trading codes (e.g., 'BATBC,SQURPHARMA,OLYMPIC')
     */
    codes: string;
};

export type FundamentalsCompareCompaniesResponse = (Array<CompanyComparison>);

export type FundamentalsSearchCompaniesData = {
    /**
     * Filter by category (A, B, G, N, Z)
     */
    category?: (string | null);
    /**
     * Maximum results to return
     */
    limit?: number;
    /**
     * Maximum P/E ratio
     */
    maxPe?: (number | string | null);
    /**
     * Minimum dividend yield %
     */
    minDividendYield?: (number | string | null);
    /**
     * Minimum P/E ratio
     */
    minPe?: (number | string | null);
    /**
     * Filter by sector (e.g., 'Food & Allied')
     */
    sector?: (string | null);
};

export type FundamentalsSearchCompaniesResponse = (Array<CompanySearchResult>);

export type FundamentalsCheckDataAvailabilityData = {
    tradingCode: string;
};

export type FundamentalsCheckDataAvailabilityResponse = (FundamentalDataAvailability);

export type FundsGetFundsSummaryResponse = (unknown);

export type FundsListTransactionsData = {
    limit?: number;
    offset?: number;
};

export type FundsListTransactionsResponse = (Array<AccountTransactionPublic>);

export type FundsDepositFundsData = {
    requestBody: FundsChangeRequest;
};

export type FundsDepositFundsResponse = (unknown);

export type FundsWithdrawFundsData = {
    requestBody: FundsChangeRequest;
};

export type FundsWithdrawFundsResponse = (unknown);

export type FundsUpdateFundsSettingsData = {
    requestBody: FundsSettingsRequest;
};

export type FundsUpdateFundsSettingsResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type KycGetKycInformationResponse = (KYCInformationPublic);

export type KycUpdateKycInformationData = {
    requestBody: KYCInformationUpdate;
};

export type KycUpdateKycInformationResponse = (KYCInformationPublic);

export type KycCreateKycInformationData = {
    requestBody: KYCInformationCreate;
};

export type KycCreateKycInformationResponse = (KYCInformationPublic);

export type KycGetKycStatusResponse = (unknown);

export type KycGetInvestmentGoalsResponse = (Array<UserInvestmentGoalPublic>);

export type KycCreateInvestmentGoalData = {
    requestBody: UserInvestmentGoalCreate;
};

export type KycCreateInvestmentGoalResponse = (UserInvestmentGoalPublic);

export type KycUpdateInvestmentGoalData = {
    goalId: string;
    requestBody: UserInvestmentGoalUpdate;
};

export type KycUpdateInvestmentGoalResponse = (UserInvestmentGoalPublic);

export type KycDeleteInvestmentGoalData = {
    goalId: string;
};

export type KycDeleteInvestmentGoalResponse = (unknown);

export type KycCreateGoalContributionData = {
    goalId: string;
    requestBody: UserInvestmentGoalContributionCreate;
};

export type KycCreateGoalContributionResponse = (UserInvestmentGoalContributionPublic);

export type KycListGoalContributionsData = {
    goalId: string;
};

export type KycListGoalContributionsResponse = (Array<UserInvestmentGoalContributionPublic>);

export type KycDeleteGoalContributionData = {
    contributionId: string;
};

export type KycDeleteGoalContributionResponse = (unknown);

export type KycCalculateGoalSipData = {
    goalId: string;
};

export type KycCalculateGoalSipResponse = (SIPCalculationResult);

export type KycGetGoalProgressData = {
    goalId: string;
};

export type KycGetGoalProgressResponse = (GoalProgressResponse);

export type KycCalculateWhatIfScenarioData = {
    goalId: string;
    requestBody: WhatIfScenarioRequest;
};

export type KycCalculateWhatIfScenarioResponse = (WhatIfScenarioResponse);

export type KycGetAssetAllocationRecommendationData = {
    goalId: string;
};

export type KycGetAssetAllocationRecommendationResponse = (AssetAllocationRecommendation);

export type KycGetProductRecommendationsData = {
    goalId: string;
};

export type KycGetProductRecommendationsResponse = (ProductRecommendationResponse);

export type KycGetGoalAlertsData = {
    goalId: string;
};

export type KycGetGoalAlertsResponse = (GoalAlertResponse);

export type KycGetUserAccountsResponse = (Array<UserAccountPublic>);

export type KycCreateUserAccountData = {
    requestBody: UserAccountCreate;
};

export type KycCreateUserAccountResponse = (UserAccountPublic);

export type KycUpdateUserAccountData = {
    accountId: string;
    requestBody: UserAccountUpdate;
};

export type KycUpdateUserAccountResponse = (UserAccountPublic);

export type KycDeleteUserAccountData = {
    accountId: string;
};

export type KycDeleteUserAccountResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MarketGetMarketSummaryResponse = ({
    [key: string]: unknown;
});

export type MarketListStocksData = {
    limit?: number;
    offset?: number;
    /**
     * Search by symbol or company name
     */
    q?: (string | null);
    sector?: (string | null);
};

export type MarketListStocksResponse = (Array<{
    [key: string]: unknown;
}>);

export type MarketGetStockData = {
    symbol: string;
};

export type MarketGetStockResponse = ({
    [key: string]: unknown;
});

export type MarketGetChartDataData = {
    symbol: string;
    /**
     * 1D (intraday ticks), 1W, 1M, 3M, 6M, 1Y, 2Y, 5Y, ALL for daily OHLC
     */
    timeframe?: string;
};

export type MarketGetChartDataResponse = ({
    [key: string]: unknown;
});

export type MarketGetTopMoversData = {
    limit?: number;
};

export type MarketGetTopMoversResponse = ({
    [key: string]: Array<{
        [key: string]: unknown;
    }>;
});

export type MarketGetMostActiveData = {
    limit?: number;
};

export type MarketGetMostActiveResponse = (Array<{
    [key: string]: unknown;
}>);

export type MarketGetIndicesData = {
    days?: number;
};

export type MarketGetIndicesResponse = ({
    [key: string]: unknown;
});

export type MarketGetTurnoverCompareResponse = ({
    [key: string]: unknown;
});

export type MarketGetMarketFlowsResponse = ({
    [key: string]: unknown;
});

export type MarketGetMacroSnapshotResponse = ({
    [key: string]: unknown;
});

export type MarketGetUpcomingEventsData = {
    limit?: number;
};

export type MarketGetUpcomingEventsResponse = ({
    [key: string]: unknown;
});

export type NewsListNewsData = {
    category?: (string | null);
    days?: number;
    limit?: number;
    offset?: number;
};

export type NewsListNewsResponse = (Array<NewsPublic>);

export type NewsCreateNewsData = {
    requestBody: NewsCreate;
};

export type NewsCreateNewsResponse = (NewsPublic);

export type NewsGetStockNewsData = {
    days?: number;
    symbol: string;
};

export type NewsGetStockNewsResponse = (Array<NewsPublic>);

export type OrdersCreateOrderData = {
    requestBody: OrderCreate;
};

export type OrdersCreateOrderResponse = (OrderPublic);

export type OrdersGetUserOrdersData = {
    portfolioId?: (string | null);
    status?: (OrderStatus | null);
};

export type OrdersGetUserOrdersResponse = (Array<OrderPublic>);

export type OrdersGetUserOrdersWithDetailsData = {
    portfolioId?: (string | null);
    status?: (OrderStatus | null);
};

export type OrdersGetUserOrdersWithDetailsResponse = (Array<OrderWithDetails>);

export type OrdersGetOrderData = {
    orderId: string;
};

export type OrdersGetOrderResponse = (OrderPublic);

export type OrdersUpdateOrderData = {
    orderId: string;
    requestBody: OrderUpdate;
};

export type OrdersUpdateOrderResponse = (OrderPublic);

export type OrdersCancelOrderData = {
    orderId: string;
};

export type OrdersCancelOrderResponse = (unknown);

export type OrdersGetOrderExecutionsData = {
    orderId: string;
};

export type OrdersGetOrderExecutionsResponse = (Array<OrderExecutionPublic>);

export type OrdersGetOrderSummaryData = {
    portfolioId?: (string | null);
};

export type OrdersGetOrderSummaryResponse = (OrderSummary);

export type PerformanceGetPortfolioReturnsData = {
    period?: string;
    portfolioId: string;
};

export type PerformanceGetPortfolioReturnsResponse = (unknown);

export type PerformanceGetRiskMetricsData = {
    benchmarkId?: (string | null);
    period?: string;
    portfolioId: string;
};

export type PerformanceGetRiskMetricsResponse = (RiskMetricsResponse);

export type PerformanceGetPortfolioBestWorstPeriodsData = {
    period?: string;
    portfolioId: string;
};

export type PerformanceGetPortfolioBestWorstPeriodsResponse = (unknown);

export type PerformanceGetCashFlowAnalysisData = {
    period?: string;
    portfolioId: string;
    transactionType?: string;
};

export type PerformanceGetCashFlowAnalysisResponse = (unknown);

export type PerformanceGetPortfolioCurrentValueData = {
    portfolioId: string;
};

export type PerformanceGetPortfolioCurrentValueResponse = (unknown);

export type PerformanceGetPortfolioPerformanceSummaryData = {
    period?: string;
    portfolioId: string;
};

export type PerformanceGetPortfolioPerformanceSummaryResponse = (PerformanceSummaryResponse);

export type PerformanceGetPortfolioValueHistoryData = {
    benchmarkId?: (string | null);
    frequency?: string;
    period?: string;
    portfolioId: string;
};

export type PerformanceGetPortfolioValueHistoryResponse = (ValueHistoryResponse);

export type PerformanceGetBenchmarkComparisonData = {
    benchmarkId?: string;
    portfolioId: string;
};

export type PerformanceGetBenchmarkComparisonResponse = (BenchmarkComparisonResponse);

export type PerformanceGetAvailableBenchmarksResponse = (BenchmarkListResponse);

export type PerformanceGetMonthlyReturnsData = {
    portfolioId: string;
    year?: (number | null);
};

export type PerformanceGetMonthlyReturnsResponse = (MonthlyReturnsResponse);

export type PerformanceGetAssetClassAttributionData = {
    period?: string;
    portfolioId: string;
};

export type PerformanceGetAssetClassAttributionResponse = (AttributionResponse);

export type PerformanceGetSectorAttributionData = {
    benchmarkId?: (string | null);
    period?: string;
    portfolioId: string;
};

export type PerformanceGetSectorAttributionResponse = (AttributionResponse);

export type PerformanceGetSecurityAttributionData = {
    limit?: number;
    period?: string;
    portfolioId: string;
};

export type PerformanceGetSecurityAttributionResponse = (unknown);

export type PerformanceGetReturnDecompositionData = {
    period?: string;
    portfolioId: string;
};

export type PerformanceGetReturnDecompositionResponse = (unknown);

export type PerformanceGetPeriodPerformanceData = {
    portfolioId: string;
};

export type PerformanceGetPeriodPerformanceResponse = (unknown);

export type PerformanceBackfillPortfolioValuationsData = {
    /**
     * Number of days to backfill if start_date not provided
     */
    days?: number;
    portfolioId: string;
    /**
     * Start date for backfill
     */
    startDate?: (string | null);
};

export type PerformanceBackfillPortfolioValuationsResponse = (unknown);

export type PerformanceBackfillAllPortfoliosData = {
    /**
     * Number of days to backfill
     */
    days?: number;
};

export type PerformanceBackfillAllPortfoliosResponse = (unknown);

export type PortfolioGetUserPortfoliosResponse = (Array<PortfolioPublic>);

export type PortfolioCreatePortfolioData = {
    requestBody: PortfolioCreate;
};

export type PortfolioCreatePortfolioResponse = (PortfolioPublic);

export type PortfolioGetPortfolioData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioResponse = (PortfolioPublic);

export type PortfolioUpdatePortfolioData = {
    portfolioId: string;
    requestBody: PortfolioUpdate;
};

export type PortfolioUpdatePortfolioResponse = (PortfolioPublic);

export type PortfolioDeletePortfolioData = {
    portfolioId: string;
};

export type PortfolioDeletePortfolioResponse = (unknown);

export type PortfolioAddPositionData = {
    averagePrice: number;
    portfolioId: string;
    quantity: number;
    stockSymbol: string;
};

export type PortfolioAddPositionResponse = (PortfolioPositionPublic);

export type PortfolioGetPortfolioPositionsData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioPositionsResponse = (Array<PortfolioPositionPublic>);

export type PortfolioGetPositionsBySymbolData = {
    symbol: string;
};

export type PortfolioGetPositionsBySymbolResponse = (unknown);

export type PortfolioGetPortfolioPositionsWithDetailsData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioPositionsWithDetailsResponse = (unknown);

export type PortfolioUpdatePositionData = {
    averagePrice?: (number | null);
    portfolioId: string;
    positionId: string;
    quantity?: (number | null);
};

export type PortfolioUpdatePositionResponse = (unknown);

export type PortfolioRemovePositionData = {
    portfolioId: string;
    positionId: string;
};

export type PortfolioRemovePositionResponse = (unknown);

export type PortfolioAddTradeData = {
    portfolioId: string;
    requestBody: TradeCreate;
};

export type PortfolioAddTradeResponse = (TradePublic);

export type PortfolioGetPortfolioTradesData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioTradesResponse = (Array<TradePublic>);

export type PortfolioUpdateTradeData = {
    portfolioId: string;
    requestBody: TradeUpdate;
    tradeId: string;
};

export type PortfolioUpdateTradeResponse = (TradePublic);

export type PortfolioDeleteTradeData = {
    portfolioId: string;
    tradeId: string;
};

export type PortfolioDeleteTradeResponse = (unknown);

export type PortfolioGetPortfolioSummaryData = {
    portfolioId: string;
};

export type PortfolioGetPortfolioSummaryResponse = (PortfolioSummary);

export type PortfolioGetRecentTradesData = {
    limit?: number;
};

export type PortfolioGetRecentTradesResponse = (Array<TradeWithDetails>);

export type PortfolioGetOrdersTradesSummaryResponse = (unknown);

export type PortfolioUploadPortfolioStatementData = {
    brokerHouse?: (string | null);
    formData: Body_portfolio_upload_portfolio_statement;
    portfolioId: string;
};

export type PortfolioUploadPortfolioStatementResponse = (PortfolioStatementResponse);

export type PortfolioSaveBulkHoldingsData = {
    portfolioId: string;
    requestBody: BulkHoldingsSaveRequest;
};

export type PortfolioSaveBulkHoldingsResponse = (BulkHoldingsSaveResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RebalancingGetRebalancingSuggestionsData = {
    /**
     * Minimum trade value
     */
    minTradeValue?: number;
    portfolioId: string;
    /**
     * Rebalancing strategy
     */
    strategy?: string;
    /**
     * Drift threshold percentage
     */
    thresholdPct?: number;
};

export type RebalancingGetRebalancingSuggestionsResponse = (RebalancingSuggestionsResponse);

export type RebalancingExecuteRebalancingData = {
    portfolioId: string;
    requestBody: RebalancingExecuteRequest;
};

export type RebalancingExecuteRebalancingResponse = (RebalancingExecuteResponse);

export type RebalancingGetRebalancingHistoryData = {
    limit?: number;
    offset?: number;
    portfolioId: string;
};

export type RebalancingGetRebalancingHistoryResponse = (RebalancingHistoryResponse);

export type RebalancingGetRebalancingSettingsData = {
    portfolioId: string;
};

export type RebalancingGetRebalancingSettingsResponse = (RebalancingSettingsPublic);

export type RebalancingUpdateRebalancingSettingsData = {
    portfolioId: string;
    requestBody: RebalancingSettingsUpdate;
};

export type RebalancingUpdateRebalancingSettingsResponse = (RebalancingSettingsPublic);

export type ResearchStockScreenerData = {
    /**
     * Industry filter
     */
    industry?: (string | null);
    /**
     * Maximum number of results
     */
    limit?: number;
    /**
     * Maximum dividend yield %
     */
    maxDividendYield?: (number | null);
    /**
     * Maximum market cap in millions
     */
    maxMarketCap?: (number | null);
    /**
     * Maximum P/E ratio
     */
    maxPeRatio?: (number | null);
    /**
     * Maximum stock price
     */
    maxPrice?: (number | null);
    /**
     * Maximum daily price change percent
     */
    maxPriceChange?: (number | null);
    /**
     * Maximum price-to-book ratio
     */
    maxPriceToBook?: (number | null);
    /**
     * Maximum RSI value
     */
    maxRsi?: (number | null);
    /**
     * Minimum dividend yield %
     */
    minDividendYield?: (number | null);
    /**
     * Minimum market cap in millions
     */
    minMarketCap?: (number | null);
    /**
     * Minimum P/E ratio
     */
    minPeRatio?: (number | null);
    /**
     * Minimum stock price
     */
    minPrice?: (number | null);
    /**
     * Minimum daily price change percent
     */
    minPriceChange?: (number | null);
    /**
     * Minimum price-to-book ratio
     */
    minPriceToBook?: (number | null);
    /**
     * Minimum RSI value
     */
    minRsi?: (number | null);
    /**
     * Minimum average volume
     */
    minVolume?: (number | null);
    /**
     * Moving average position filter (all, above_20, above_50, below_20, below_50)
     */
    movingAverage?: (string | null);
    /**
     * Sector filter
     */
    sector?: (string | null);
};

export type ResearchStockScreenerResponse = (unknown);

export type ResearchGetFundamentalAnalysisData = {
    symbol: string;
};

export type ResearchGetFundamentalAnalysisResponse = (unknown);

export type ResearchGetTechnicalAnalysisData = {
    /**
     * Number of days for analysis
     */
    period?: number;
    symbol: string;
};

export type ResearchGetTechnicalAnalysisResponse = (unknown);

export type ResearchGetStockNewsData = {
    /**
     * Number of news articles to return
     */
    limit?: number;
    symbol: string;
};

export type ResearchGetStockNewsResponse = (unknown);

export type ResearchGetSectorAnalysisResponse = (unknown);

export type ResearchGetStockOfTheDayResponse = (unknown);

export type ResearchGetAnalystPicksData = {
    limit?: number;
};

export type ResearchGetAnalystPicksResponse = (unknown);

export type ResearchGetEarningsHighlightsData = {
    limit?: number;
};

export type ResearchGetEarningsHighlightsResponse = (unknown);

export type ResearchGetThematicIdeasResponse = (unknown);

export type RiskManagementGetUserRiskProfileResponse = (UserRiskProfilePublic);

export type RiskManagementCreateUserRiskProfileData = {
    requestBody: UserRiskProfileCreate;
};

export type RiskManagementCreateUserRiskProfileResponse = (UserRiskProfilePublic);

export type RiskManagementGetRiskAlertsData = {
    isActive?: (boolean | null);
    portfolioId?: (string | null);
};

export type RiskManagementGetRiskAlertsResponse = (Array<RiskAlertPublic>);

export type RiskManagementCreateStockScreenerData = {
    requestBody: StockScreenerCreate;
};

export type RiskManagementCreateStockScreenerResponse = (StockScreenerPublic);

export type RiskManagementGetStockScreenersData = {
    isActive?: (boolean | null);
};

export type RiskManagementGetStockScreenersResponse = (Array<StockScreenerPublic>);

export type SubscriptionsListPlansResponse = (Array<SubscriptionPlanPublic>);

export type SubscriptionsCreatePlanData = {
    requestBody: SubscriptionPlanCreate;
};

export type SubscriptionsCreatePlanResponse = (SubscriptionPlanPublic);

export type SubscriptionsSubscribeData = {
    requestBody: UserSubscriptionCreate;
};

export type SubscriptionsSubscribeResponse = (UserSubscriptionPublic);

export type SubscriptionsStatusCheckResponse = (SubscriptionStatus);

export type SubscriptionsBkashPaymentData = {
    requestBody: PaymentRequest;
};

export type SubscriptionsBkashPaymentResponse = (PaymentResponse);

export type TradingviewGetConfigResponse = ({
    [key: string]: unknown;
});

export type TradingviewSearchSymbolsData = {
    /**
     * Exchange filter
     */
    exchange?: (string | null);
    /**
     * Maximum number of results
     */
    limit?: number;
    /**
     * Search query for symbol or company name
     */
    query?: (string | null);
    /**
     * Symbol name for individual symbol resolution
     */
    symbol?: (string | null);
    /**
     * Type filter (stock, index, etc)
     */
    type?: (string | null);
};

export type TradingviewSearchSymbolsResponse = (({
    [key: string]: unknown;
} | Array<{
    [key: string]: unknown;
}>));

export type TradingviewSearchSymbolsSearchData = {
    /**
     * Exchange filter
     */
    exchange?: (string | null);
    /**
     * Maximum number of results
     */
    limit?: number;
    /**
     * Search query for symbol or company name
     */
    query?: (string | null);
    /**
     * Type filter (stock, index, etc)
     */
    type?: (string | null);
};

export type TradingviewSearchSymbolsSearchResponse = (Array<{
    [key: string]: unknown;
}>);

export type TradingviewGetSymbolInfoData = {
    /**
     * Exchange group
     */
    group?: (string | null);
};

export type TradingviewGetSymbolInfoResponse = ({
    [key: string]: unknown;
});

export type TradingviewGetHistoryData = {
    /**
     * Number of bars to return
     */
    countback?: (number | null);
    /**
     * Unix timestamp (seconds) of the leftmost bar
     */
    from: number;
    /**
     * Resolution (1D, 1W, 1M, etc)
     */
    resolution: string;
    /**
     * Symbol name
     */
    symbol: string;
    /**
     * Unix timestamp (seconds) of the rightmost bar
     */
    to: number;
};

export type TradingviewGetHistoryResponse = ({
    [key: string]: unknown;
});

export type TradingviewGetQuotesData = {
    /**
     * Comma-separated list of symbols
     */
    symbols: string;
};

export type TradingviewGetQuotesResponse = ({
    [key: string]: unknown;
});

export type TradingviewGetPositionsForTradingviewData = {
    symbol: string;
};

export type TradingviewGetPositionsForTradingviewResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WatchlistGetUserWatchlistsResponse = (Array<WatchlistPublic>);

export type WatchlistCreateWatchlistData = {
    requestBody: WatchlistCreate;
};

export type WatchlistCreateWatchlistResponse = (WatchlistPublic);

export type WatchlistGetWatchlistData = {
    watchlistId: string;
};

export type WatchlistGetWatchlistResponse = (WatchlistPublic);

export type WatchlistUpdateWatchlistData = {
    requestBody: WatchlistUpdate;
    watchlistId: string;
};

export type WatchlistUpdateWatchlistResponse = (WatchlistPublic);

export type WatchlistDeleteWatchlistData = {
    watchlistId: string;
};

export type WatchlistDeleteWatchlistResponse = (unknown);

export type WatchlistAddWatchlistItemData = {
    requestBody: WatchlistItemCreate;
    watchlistId: string;
};

export type WatchlistAddWatchlistItemResponse = (WatchlistItemPublic);

export type WatchlistGetWatchlistItemsData = {
    watchlistId: string;
};

export type WatchlistGetWatchlistItemsResponse = (Array<WatchlistItemPublic>);

export type WatchlistUpdateWatchlistItemData = {
    itemId: string;
    notes?: (string | null);
    watchlistId: string;
};

export type WatchlistUpdateWatchlistItemResponse = (WatchlistItemPublic);

export type WatchlistRemoveWatchlistItemData = {
    itemId: string;
    watchlistId: string;
};

export type WatchlistRemoveWatchlistItemResponse = (unknown);

export type WatchlistAddMultipleStocksData = {
    requestBody: Array<(string)>;
    watchlistId: string;
};

export type WatchlistAddMultipleStocksResponse = (unknown);

export type WatchlistRemoveMultipleStocksData = {
    requestBody: BulkRemoveRequest;
    watchlistId: string;
};

export type WatchlistRemoveMultipleStocksResponse = (unknown);

export type WatchlistAddMultipleBySymbolsData = {
    requestBody: BulkSymbolsRequest;
    watchlistId: string;
};

export type WatchlistAddMultipleBySymbolsResponse = (unknown);

export type WatchlistSearchStocksData = {
    limit?: number;
    query: string;
};

export type WatchlistSearchStocksResponse = (unknown);

export type WatchlistGetWatchlistItemsWithDetailsData = {
    watchlistId: string;
};

export type WatchlistGetWatchlistItemsWithDetailsResponse = (unknown);