"""Add trading ideas feature tables

Revision ID: 1dfe48305639
Revises: a5f6300d3323
Create Date: 2025-12-19 22:14:38.441923

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1dfe48305639'
down_revision = 'a5f6300d3323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_follow',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_follow_symbol'), 'symbol_follow', ['symbol'], unique=False)
    op.create_index(op.f('ix_symbol_follow_user_id'), 'symbol_follow', ['user_id'], unique=False)
    op.create_table('trading_idea',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('timeframe', sa.Enum('M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1', 'MN1', name='ideatimeframe'), nullable=True),
    sa.Column('bias', sa.Enum('LONG', 'SHORT', 'NEUTRAL', name='ideabias'), nullable=True),
    sa.Column('chart_state', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_idea_is_published'), 'trading_idea', ['is_published'], unique=False)
    op.create_index(op.f('ix_trading_idea_user_id'), 'trading_idea', ['user_id'], unique=False)
    op.create_table('user_follow',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('followed_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_follow_followed_id'), 'user_follow', ['followed_id'], unique=False)
    op.create_index(op.f('ix_user_follow_follower_id'), 'user_follow', ['follower_id'], unique=False)
    op.create_table('idea_comment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idea_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['trading_idea.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_comment_idea_id'), 'idea_comment', ['idea_id'], unique=False)
    op.create_index(op.f('ix_idea_comment_user_id'), 'idea_comment', ['user_id'], unique=False)
    op.create_table('idea_like',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idea_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['trading_idea.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_like_idea_id'), 'idea_like', ['idea_id'], unique=False)
    op.create_index(op.f('ix_idea_like_user_id'), 'idea_like', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idea_like_user_id'), table_name='idea_like')
    op.drop_index(op.f('ix_idea_like_idea_id'), table_name='idea_like')
    op.drop_table('idea_like')
    op.drop_index(op.f('ix_idea_comment_user_id'), table_name='idea_comment')
    op.drop_index(op.f('ix_idea_comment_idea_id'), table_name='idea_comment')
    op.drop_table('idea_comment')
    op.drop_index(op.f('ix_user_follow_follower_id'), table_name='user_follow')
    op.drop_index(op.f('ix_user_follow_followed_id'), table_name='user_follow')
    op.drop_table('user_follow')
    op.drop_index(op.f('ix_trading_idea_user_id'), table_name='trading_idea')
    op.drop_index(op.f('ix_trading_idea_is_published'), table_name='trading_idea')
    op.drop_table('trading_idea')
    op.drop_index(op.f('ix_symbol_follow_user_id'), table_name='symbol_follow')
    op.drop_index(op.f('ix_symbol_follow_symbol'), table_name='symbol_follow')
    op.drop_table('symbol_follow')
    # ### end Alembic commands ###
