"""Initial merged migration

Revision ID: 7e8646cea0c8
Revises: 
Create Date: 2025-07-23 15:54:52.929599

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e8646cea0c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('trading_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('scrip_code', sa.Integer(), nullable=True),
    sa.Column('type_of_instrument', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('market_category', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('electronic_share', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('authorized_capital', sa.Float(), nullable=True),
    sa.Column('paid_up_capital', sa.Float(), nullable=True),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('market_lot', sa.Integer(), nullable=True),
    sa.Column('total_outstanding_securities', sa.Integer(), nullable=True),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('debut_trading_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listing_year', sa.Integer(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=2500), nullable=True),
    sa.Column('factory_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('fax', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('company_secretary_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('company_secretary_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('company_secretary_cell_no', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reserve_and_surplus', sa.Float(), nullable=True),
    sa.Column('year_end', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('last_agm_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fifty_two_weeks_moving_range', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('trading_code')
    )
    op.create_table('marketsummary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Integer(), nullable=False),
    sa.Column('total_turnover', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('dse_index', sa.Numeric(), nullable=True),
    sa.Column('dse_index_change', sa.Numeric(), nullable=True),
    sa.Column('dse_index_change_percent', sa.Numeric(), nullable=True),
    sa.Column('cse_index', sa.Numeric(), nullable=True),
    sa.Column('cse_index_change', sa.Numeric(), nullable=True),
    sa.Column('cse_index_change_percent', sa.Numeric(), nullable=True),
    sa.Column('advancers', sa.Integer(), nullable=False),
    sa.Column('decliners', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketsummary_date'), 'marketsummary', ['date'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paymentgateway',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockcompany',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('authorized_capital', sa.Numeric(), nullable=True),
    sa.Column('paid_up_capital', sa.Numeric(), nullable=True),
    sa.Column('face_value', sa.Numeric(), nullable=True),
    sa.Column('total_shares', sa.Integer(), nullable=True),
    sa.Column('free_float', sa.Numeric(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(), nullable=True),
    sa.Column('eps', sa.Numeric(), nullable=True),
    sa.Column('nav', sa.Numeric(), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockcompany_symbol'), 'stockcompany', ['symbol'], unique=True)
    op.create_table('subscriptionplan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('alert',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('notification_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stockcompany.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailyohlc',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('turnover', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('change', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['stockcompany.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailyohlc_date'), 'dailyohlc', ['date'], unique=False)
    op.create_table('intradaytick',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['stockcompany.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketinformation',
    sa.Column('market_info_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('last_trading_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closing_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('opening_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('adjusted_opening_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('days_range', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('change', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('days_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('days_volume', sa.Integer(), nullable=True),
    sa.Column('days_trade', sa.Integer(), nullable=True),
    sa.Column('market_capitalization', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('yesterday_closing_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('market_info_id')
    )
    op.create_index(op.f('ix_marketinformation_company_id'), 'marketinformation', ['company_id'], unique=False)
    op.create_table('marketnews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('news_id', sa.Uuid(), nullable=False),
    sa.Column('market_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('impact_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockdata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('last_trade_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('change_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('turnover', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['stockcompany.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocknews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('news_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stockcompany.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usernewspreference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_digest', sa.Boolean(), nullable=False),
    sa.Column('digest_frequency', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersubscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscriptionplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertnotification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('gateway_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['usersubscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('portfolioposition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_investment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unrealized_pnl_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stockcompany.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('trade_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stockcompany.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlistitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('watchlist_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stockcompany.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlistitem')
    op.drop_table('trade')
    op.drop_table('portfolioposition')
    op.drop_table('payment')
    op.drop_table('alertnotification')
    op.drop_table('watchlist')
    op.drop_table('usersubscription')
    op.drop_table('usernewspreference')
    op.drop_table('stocknews')
    op.drop_table('stockdata')
    op.drop_table('portfolio')
    op.drop_table('marketnews')
    op.drop_index(op.f('ix_marketinformation_company_id'), table_name='marketinformation')
    op.drop_table('marketinformation')
    op.drop_table('item')
    op.drop_table('intradaytick')
    op.drop_index(op.f('ix_dailyohlc_date'), table_name='dailyohlc')
    op.drop_table('dailyohlc')
    op.drop_table('alert')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('subscriptionplan')
    op.drop_index(op.f('ix_stockcompany_symbol'), table_name='stockcompany')
    op.drop_table('stockcompany')
    op.drop_table('paymentgateway')
    op.drop_table('news')
    op.drop_index(op.f('ix_marketsummary_date'), table_name='marketsummary')
    op.drop_table('marketsummary')
    op.drop_table('company')
    # ### end Alembic commands ###
