"""change_volume_to_bigint

Revision ID: 7fbb10dd9eaa
Revises: 7e8646cea0c8
Create Date: 2025-07-23 16:43:55.104749

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7fbb10dd9eaa'
down_revision = '7e8646cea0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
