"""add_order_tables

Revision ID: db01ebeeaeb1
Revises: ea5530c74046
Create Date: 2025-07-28 16:43:26.949661

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'db01ebeeaeb1'
down_revision = 'ea5530c74046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertype'), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', 'PENDING_CANCEL', name='orderstatus'), nullable=False),
    sa.Column('validity', sa.Enum('DAY', 'GTC', 'IOC', 'FOK', name='ordervalidity'), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('exchange_order_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stockcompany.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderexecution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('exchange_trade_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('intradaytick', 'volume',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('marketsummary', 'total_volume',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('stockdata', 'volume',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stockdata', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('marketsummary', 'total_volume',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('intradaytick', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_table('orderexecution')
    op.drop_table('order')
    # ### end Alembic commands ###
