"""increase_symbol_length_to_50

Revision ID: ea5530c74046
Revises: bbbbc25c8827
Create Date: 2025-07-24 16:46:47.724572

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea5530c74046'
down_revision = 'bbbbc25c8827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only change the symbol length, keep volume fields as BIGINT
    op.alter_column('stockcompany', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only revert the symbol length change
    op.alter_column('stockcompany', 'symbol',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
