"""add_risk_management_models

Revision ID: fc41cbbd796f
Revises: db01ebeeaeb1
Create Date: 2025-08-02 22:36:36.574989

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc41cbbd796f'
down_revision = 'db01ebeeaeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockscreener',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userriskprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('risk_profile', sa.Enum('CONSERVATIVE', 'MODERATE', 'AGGRESSIVE', name='riskprofile'), nullable=False),
    sa.Column('max_portfolio_volatility', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_single_position', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_sector_concentration', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_sharpe_ratio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_drawdown_tolerance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolioriskmetrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.Column('volatility', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('beta', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('var_95', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cvar_95', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('top_5_concentration', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sector_concentration', sa.JSON(), nullable=True),
    sa.Column('avg_correlation', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('correlation_matrix', sa.JSON(), nullable=True),
    sa.Column('risk_alerts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riskalert',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('dailyohlc', 'volume',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dailyohlc', 'volume',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_table('riskalert')
    op.drop_table('portfolioriskmetrics')
    op.drop_table('userriskprofile')
    op.drop_table('stockscreener')
    # ### end Alembic commands ###
