/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutWatchlistImport } from './routes/_layout/watchlist'
import { Route as LayoutTradingImport } from './routes/_layout/trading'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutPortfolioImport } from './routes/_layout/portfolio'
import { Route as LayoutOrdersImport } from './routes/_layout/orders'
import { Route as LayoutMarketImport } from './routes/_layout/market'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutAdminImport } from './routes/_layout/admin'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutWatchlistRoute = LayoutWatchlistImport.update({
  path: '/watchlist',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTradingRoute = LayoutTradingImport.update({
  path: '/trading',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPortfolioRoute = LayoutPortfolioImport.update({
  path: '/portfolio',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrdersRoute = LayoutOrdersImport.update({
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMarketRoute = LayoutMarketImport.update({
  path: '/market',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/market': {
      preLoaderRoute: typeof LayoutMarketImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/orders': {
      preLoaderRoute: typeof LayoutOrdersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/portfolio': {
      preLoaderRoute: typeof LayoutPortfolioImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/trading': {
      preLoaderRoute: typeof LayoutTradingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/watchlist': {
      preLoaderRoute: typeof LayoutWatchlistImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutItemsRoute,
    LayoutMarketRoute,
    LayoutOrdersRoute,
    LayoutPortfolioRoute,
    LayoutSettingsRoute,
    LayoutTradingRoute,
    LayoutWatchlistRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
